// data.js
// MiniStep の「名言」と「チャレンジ」定義（10x 拡張版）
// Quotes: 400 / Challenges: 720 (120 per category × 6)

window.MINISTEP_DATA = {
    // ========= Daily quotes (400) =========
    quotes: [
        // --- 最初の40件 ---
        { text: "大きな変化は、ほんの小さな一歩から始まる。", author: "MiniStep" },
        { text: "完璧じゃなくていい。少しだけ前に進もう。", author: "MiniStep" },
        { text: "調子が悪い日の一歩が、いちばん大切な一歩。", author: "MiniStep" },
        { text: "昨日より少し優しく、そして1センチだけ前へ。", author: "MiniStep" },
        { text: "継続の秘訣は、やりすぎないこと。", author: "MiniStep" },
        { text: "きつい日は、できなかったことではなく、できたことを数えよう。", author: "MiniStep" },
        { text: "大きな勝利は必要ない。小さな勝利が静かに積み重なっていく。", author: "MiniStep" },
        { text: "未来の自分が、今日の小さな行動に感謝するよ。", author: "MiniStep" },
        { text: "調子のいい日は前に進む。悪い日は、ただやめないだけでいい。", author: "MiniStep" },
        { text: "本当の変化は、大きな感動からではなく、小さな習慣から生まれる。", author: "MiniStep" },
        { text: "やめた自分を責めるより、戻ってきた自分を褒めよう。", author: "MiniStep" },
        { text: "今日、自分に優しくできたなら、それは進歩だ。", author: "MiniStep" },
        { text: "比べるのは他人じゃなく、昨日の自分だけでいい。", author: "MiniStep" },
        { text: "人生はゼロか百かじゃない。今日は10%でも十分。", author: "MiniStep" },
        { text: "二歩進んで一歩下がっても、一歩は前に進んでいる。", author: "MiniStep" },
        { text: "やる気を待つな。始めれば、やる気はついてくる。", author: "MiniStep" },
        { text: "調子が悪い日は、ハードルを床まで下げていい。", author: "MiniStep" },
        { text: "小さな行動は他人には見えない。でも、あなたの人生を変えていく。", author: "MiniStep" },
        { text: "最も大切なスキルは、「今日はこれで十分」と言えること。", author: "MiniStep" },
        { text: "穏やかな継続は、激しい燃え尽きに必ず勝る。", author: "MiniStep" },
        { text: "休息は進歩の反対ではなく、進歩の一部だ。", author: "MiniStep" },
        { text: "たとえ止まっても、戻ってきた日が勝利の日。", author: "MiniStep" },
        { text: "自己信頼は、自分との小さな約束を守ることで育つ。", author: "MiniStep" },
        { text: "3回出直しても、3回挑戦したということ。それが勇気。", author: "MiniStep" },
        { text: "「絶対やめない」と言わなくていい。ただ「また戻ってくる」と言えばいい。", author: "MiniStep" },
        { text: "今日100点を取る必要はない。51点で十分すぎるくらい。", author: "MiniStep" },
        { text: "いつか振り返ったとき、今日の小さな一歩が転換点だったと気づく。", author: "MiniStep" },
        { text: "頑張れない日は、エネルギーを守ることに集中しよう。", author: "MiniStep" },
        { text: "今日このアプリを開いた。それだけで一歩踏み出している。", author: "MiniStep" },
        { text: "「継続する」を、勝てる小さなゲームにしよう。", author: "MiniStep" },
        { text: "朝の3分が、夜の30分を救うかもしれない。", author: "MiniStep" },
        { text: "今日のしぶしぶの一歩が、未来の自分をストレスから守る。", author: "MiniStep" },
        { text: "小さなチャレンジは、未来の自分への小さなプレゼント。", author: "MiniStep" },
        { text: "うまくやることより、やってみることの方が大事。", author: "MiniStep" },
        { text: "自分を追い込む日と、自分に優しくする日、両方あっていい。", author: "MiniStep" },
        { text: "今日の小さな一歩は、完全に止まっていない証拠。", author: "MiniStep" },
        { text: "頑張り屋さんの次のスキルは、やめるタイミングを知ること。", author: "MiniStep" },
        { text: "変わりたいと思うこと、それがすでに変化の始まり。", author: "MiniStep" },
        { text: "動けない日は、せめて「これだけはしない」を一つ決めよう。", author: "MiniStep" },
        { text: "悪い日は一ページにすぎない。物語全体じゃない。", author: "MiniStep" },

        // --- 自己慈悲 (41-80) ---
        { text: "苦しんでいる友人に接するように、自分自身にも接しよう。", author: "MiniStep" },
        { text: "これまでの「最悪の日」をすべて乗り越えてきた。それは本当にすごいこと。", author: "MiniStep" },
        { text: "自分に優しくするのは怠惰じゃない。それは戦略だ。", author: "MiniStep" },
        { text: "場所を取っていい。ゆっくり進んでいい。", author: "MiniStep" },
        { text: "回復は直線じゃない。休む日もあれば、跳び上がる日もある。", author: "MiniStep" },
        { text: "あなたのペースはあなたのもの。他の人のスケジュールは関係ない。", author: "MiniStep" },
        { text: "もがくことは失敗じゃない。成長しているということ。", author: "MiniStep" },
        { text: "誰かに変身の物語を見せる義務はない。ただ、あるがままでいい。", author: "MiniStep" },
        { text: "壊れる前に休憩が必要なのは、当然のこと。", author: "MiniStep" },
        { text: "「自分には価値がない」という声は嘘。今日、ちゃんとここにいるじゃないか。", author: "MiniStep" },
        { text: "歩き方を覚える子どもに与えるような忍耐を、自分にも与えよう。", author: "MiniStep" },
        { text: "毎日が生産的である必要はない。ただ生き延びればいい日もある。", author: "MiniStep" },
        { text: "あなたは遅れていない。あなたの旅が必要とする場所に、ちょうどいる。", author: "MiniStep" },
        { text: "自己慈悲は良い行動へのご褒美ではない。毎日の習慣だ。", author: "MiniStep" },
        { text: "穏やかな日が必要だと認めるのには、勇気がいる。", author: "MiniStep" },
        { text: "今日のベストが昨日のベストと違っていてもいい。それでいい。", author: "MiniStep" },
        { text: "自分の価値を成果で測るのをやめよう。", author: "MiniStep" },
        { text: "今日できる最も優しいことは、自分を許すことかもしれない。", author: "MiniStep" },
        { text: "「十分によい」は、立派な基準だ。", author: "MiniStep" },
        { text: "休息は勝ち取るものじゃない。今すぐ受け取る価値がある。", author: "MiniStep" },
        { text: "花にも雨が必要。辛い日はあなたの中の美しいものに水をやっている。", author: "MiniStep" },
        { text: "深呼吸して。あなたは自分が思うより、ずっとやっている。", author: "MiniStep" },
        { text: "良くなろうと思っていること、それがすべてを物語っている。", author: "MiniStep" },
        { text: "重いものをしばらく下ろしても、いい。", author: "MiniStep" },
        { text: "あなたは最悪の瞬間そのものじゃない。その合間の小さな努力すべてがあなただ。", author: "MiniStep" },
        { text: "見えない進歩もある。見えなくても、本物であることに変わりはない。", author: "MiniStep" },
        { text: "今日すべてを修正する必要はない。ただここにいるだけでいい。", author: "MiniStep" },
        { text: "罪悪感より休息を選ぶのは、強さの一形態だ。", author: "MiniStep" },
        { text: "柔らかさは弱さじゃない。大切なものを守る方法だ。", author: "MiniStep" },
        { text: "今日ここにいる。それだけで、何かを持ってきたということ。", author: "MiniStep" },
        { text: "すべてを理解していなくていい、と自分に許可を出そう。", author: "MiniStep" },
        { text: "結果がまだ見えなくても、あなたの努力には意味がある。", author: "MiniStep" },
        { text: "進歩はいつも直線じゃない。ジグザグもカウントされる。", author: "MiniStep" },
        { text: "今日最も勇敢なことは、何もせず、それでいいと思えることかもしれない。", author: "MiniStep" },
        { text: "小さいことは取るに足らないことじゃない。", author: "MiniStep" },
        { text: "今日、種を植えた。まだ見えないかもしれないけど、育っている。", author: "MiniStep" },
        { text: "助けを求めることは後退じゃなく、前進だ。", author: "MiniStep" },
        { text: "あなたは自分が思うより、ずっと強い。", author: "MiniStep" },
        { text: "感動させなければというプレッシャーを手放そう。ただ人間でいい。", author: "MiniStep" },
        { text: "一回の深呼吸が、次の5分を変えることができる。", author: "MiniStep" },

        // --- やる気と勢い (81-120) ---
        { text: "準備ができたと思う前に始めよう。準備は始めることでできる。", author: "MiniStep" },
        { text: "今日の1%の改善が、1年後に別人を作る。", author: "MiniStep" },
        { text: "難しいことはできる。特に、小さな難しいことなら。", author: "MiniStep" },
        { text: "エネルギーは行動の後からついてくる。逆じゃない。", author: "MiniStep" },
        { text: "一番難しいのは最初の10秒。その後は勢いがついてくる。", author: "MiniStep" },
        { text: "月曜日に新たなスタートは必要ない。今この瞬間でも始められる。", author: "MiniStep" },
        { text: "自律心は意志力じゃない。やるのが簡単なくらい工夫すること。", author: "MiniStep" },
        { text: "小さな勝利を積み重ねると、それが自信になっていく。", author: "MiniStep" },
        { text: "たまにやることより、毎日やることの方が大事。", author: "MiniStep" },
        { text: "ゼロと一の差は無限大だ。", author: "MiniStep" },
        { text: "チェーンを切らないように。でも切れたら、すぐにまたつなごう。", author: "MiniStep" },
        { text: "やる気は客人。習慣は同居人。習慣を作ろう。", author: "MiniStep" },
        { text: "避けていることの、できるだけ小さなバージョンをやってみよう。", author: "MiniStep" },
        { text: "5分のスタートは、ゼロ分の計画より優れている。", author: "MiniStep" },
        { text: "連続記録があなたを定義するんじゃない。再開することがあなたを定義する。", author: "MiniStep" },
        { text: "結果じゃなく、プロセスにコミットしよう。", author: "MiniStep" },
        { text: "今日の努力は複利で積み重なっている。まだ利息が見えないだけ。", author: "MiniStep" },
        { text: "小さな行動の繰り返しが、揺るぎないアイデンティティを作る。", author: "MiniStep" },
        { text: "目標は完璧じゃない。また現れることだ。", author: "MiniStep" },
        { text: "断れないくらい簡単にしよう。", author: "MiniStep" },
        { text: "不調なトレーニングも、しないよりまし。下手な文章も、白紙よりまし。", author: "MiniStep" },
        { text: "摩擦を減らそう。枕の上に本を置く。靴を出しておく。", author: "MiniStep" },
        { text: "習慣は、なりたい自分への投票だ。", author: "MiniStep" },
        { text: "2回連続でサボらない人になることに集中しよう。", author: "MiniStep" },
        { text: "迷ったら、3分タイマーをスタートするだけでいい。", author: "MiniStep" },
        { text: "毎日できる小さな習慣は、一度もできない大きな計画より価値がある。", author: "MiniStep" },
        { text: "ぐちゃぐちゃでも、疲れていても、ただ現れよう。", author: "MiniStep" },
        { text: "進歩は退屈な継続の中に隠れている。", author: "MiniStep" },
        { text: "行動が明確さを生む。考えすぎは混乱を生む。", author: "MiniStep" },
        { text: "すべての専門家は、ただ続けた初心者だった。", author: "MiniStep" },
        { text: "小さな一歩で滑走路を作れば、離陸は自然とついてくる。", author: "MiniStep" },
        { text: "「しなければ」を「できる」に変えてみよう。その変化を感じて。", author: "MiniStep" },
        { text: "基準を下げよう。頻度を上げよう。", author: "MiniStep" },
        { text: "これの1%バージョンはどんなもの？それをやろう。", author: "MiniStep" },
        { text: "勢いは本物だ。難しいのは最初の一歩だけ。", author: "MiniStep" },
        { text: "頂上を目指さなくていい。次の足場だけを目指そう。", author: "MiniStep" },
        { text: "毎日の小さな積み立てが、変化という財産を作る。", author: "MiniStep" },
        { text: "あなたは小さな一歩でまた連続記録を作れる。", author: "MiniStep" },
        { text: "今日は1日目か、もう1日目か。選ぶのはあなた。", author: "MiniStep" },
        { text: "階段全体が多すぎるなら、次の一段だけを見よう。", author: "MiniStep" },

        // --- 視点とマインドセット (121-160) ---
        { text: "あなたが見るすべてのものは、ひとつひとつ小さなピースで作られた。", author: "MiniStep" },
        { text: "庭を急かすことはできない。成長には自分のスケジュールがある。", author: "MiniStep" },
        { text: "頂上からの眺めは、すべての小さな登りで作られている。", author: "MiniStep" },
        { text: "季節はゆっくり変わる。人もそう。それでいい。", author: "MiniStep" },
        { text: "最高の章の多くは、「やめようと思ったけど」から始まる。", author: "MiniStep" },
        { text: "道は真っ直ぐじゃなくていい。曲がりくねった道の方が眺めがいい。", author: "MiniStep" },
        { text: "地図全体は必要ない。次の曲がり角だけでいい。", author: "MiniStep" },
        { text: "嵐の中でただ立っていることにも、力がいる。", author: "MiniStep" },
        { text: "今日重く感じることが、明日は軽く感じるかもしれない。", author: "MiniStep" },
        { text: "すべての「一夜にして成功」の裏には、千の静かな朝がある。", author: "MiniStep" },
        { text: "疑いは普通のこと。それでもやることが特別。", author: "MiniStep" },
        { text: "つまずいたら、それをダンスの一部にしよう。", author: "MiniStep" },
        { text: "すべての成長が地表に見えるわけじゃない。根も育っている。", author: "MiniStep" },
        { text: "今日不可能に思えることが、いつかウォームアップになる。", author: "MiniStep" },
        { text: "回り道は行き止まりじゃない。ただ別のルートだ。", author: "MiniStep" },
        { text: "今日の小さな一歩が、いつか人に話す一歩になるかもしれない。", author: "MiniStep" },
        { text: "ゼロから始めるんじゃない。経験から始めている。", author: "MiniStep" },
        { text: "本当に無駄な日は、自分を完全に諦めた日だけ。", author: "MiniStep" },
        { text: "遅い進歩でも、ソファに座っているすべての人を追い越している。", author: "MiniStep" },
        { text: "1%の日を1年続けたら、それは365%の成長。", author: "MiniStep" },
        { text: "価値あるものはすべて、誰かの「やってみようかな」から始まった。", author: "MiniStep" },
        { text: "混乱は理解の始まりだ。", author: "MiniStep" },
        { text: "自分の舞台裏を、他人のハイライトと比べないで。", author: "MiniStep" },
        { text: "今いる場所と行きたい場所の差は、小さな一歩で埋められる。", author: "MiniStep" },
        { text: "雨は物を育てる。あなたの雨の日も意味がある。", author: "MiniStep" },
        { text: "あなたはすでに、辛かった日の100%を生き延びた。", author: "MiniStep" },
        { text: "一つの良い決断が、一日全体を変えることができる。", author: "MiniStep" },
        { text: "どれだけゆっくりでもいい。止まらなければ。", author: "MiniStep" },
        { text: "川は一日で峡谷を刻まない。", author: "MiniStep" },
        { text: "あなたの物語はまだ終わっていない。これはただの一章。", author: "MiniStep" },
        { text: "今日の困難が明日のブレークスルーにつながるとしたら？", author: "MiniStep" },
        { text: "あなたは自分が知る以上の強さを持っている。今日がその証拠。", author: "MiniStep" },
        { text: "すべての日の出はやり直しのチャンス。優しく使おう。", author: "MiniStep" },
        { text: "日々の選択の小さな変化が、時間とともに大きな波になる。", author: "MiniStep" },
        { text: "木を植える最良の時は20年前。次に良いのは今。", author: "MiniStep" },
        { text: "プランAがうまくいかなかったら、アルファベットにはまだ25文字ある。", author: "MiniStep" },
        { text: "目標には頑固に、方法には柔軟に。", author: "MiniStep" },
        { text: "山の頂上が見えなくても、次の一歩は踏み出せる。", author: "MiniStep" },
        { text: "あなたはすでに誰かのインスピレーション。気づいていないだけ。", author: "MiniStep" },
        { text: "唯一の失敗は、再び始めないこと。", author: "MiniStep" },

        // --- 朝と夜 (161-200) ---
        { text: "朝の始め方が、その日一日にそっと語りかける。", author: "MiniStep" },
        { text: "一日があなたのエネルギーを求める前に、静かな一瞬を自分にあげよう。", author: "MiniStep" },
        { text: "良い夜は、完璧じゃなかった今日を許すことから始まる。", author: "MiniStep" },
        { text: "顔に当たる朝の光は、自然の無料リセットボタン。", author: "MiniStep" },
        { text: "眠る前の最後の考えが、明日の最初の気分を作る。", author: "MiniStep" },
        { text: "目覚めることが今日最初の達成。それを受け取ろう。", author: "MiniStep" },
        { text: "世界が押し寄せる前に、60秒の静けさを自分にあげよう。", author: "MiniStep" },
        { text: "今夜、明日の一番難しいタスクを書き留めてポケットに入れよう。", author: "MiniStep" },
        { text: "スマホのない朝は、あなただけの朝。", author: "MiniStep" },
        { text: "今日を手放そう。明日はそれ自身の贈り物を持ってくる。", author: "MiniStep" },
        { text: "世界にのばされる前に、自分でストレッチしよう。", author: "MiniStep" },
        { text: "目覚めたら、今日どんな一日にしたいか一言で決めよう。", author: "MiniStep" },
        { text: "睡眠は世界最高のやり直しボタン。賢く使おう。", author: "MiniStep" },
        { text: "最高の目覚まし時計は目的。小さなものでもいい。", author: "MiniStep" },
        { text: "寝る前に、うまくいったこと3つを挙げよう。小さなことでも。", author: "MiniStep" },
        { text: "ゆっくりとした朝は、無駄な朝じゃない。", author: "MiniStep" },
        { text: "良い本を閉じるように、感謝をもって一日を終えよう。", author: "MiniStep" },
        { text: "月は夜を急かさない。あなたも休息を急がなくていい。", author: "MiniStep" },
        { text: "ベッドを整えよう。今日頑張るという30秒の約束。", author: "MiniStep" },
        { text: "今夜の枕を、今日の悩みより柔らかくしよう。", author: "MiniStep" },
        { text: "朝のルーティンは完璧じゃなくていい。ただ自分のものであればいい。", author: "MiniStep" },
        { text: "疲れた体でも、眠る前に優しい言葉をかけてあげよう。", author: "MiniStep" },
        { text: "毎朝、白いページをもらう。一つ良いことを書こう。", author: "MiniStep" },
        { text: "夜は問題を解く時間じゃない。夜明けまで待たせよう。", author: "MiniStep" },
        { text: "明日のエネルギーは、今夜の休息から作られる。", author: "MiniStep" },
        { text: "明日、新鮮に始める許可を自分に出そう。", author: "MiniStep" },
        { text: "朝の静かな5分が、後の騒がしい5時間を救うことがある。", author: "MiniStep" },
        { text: "眠る前の感謝は、最高の子守唄。", author: "MiniStep" },
        { text: "5分早く起きよう。その時間はあなただけのもの。", author: "MiniStep" },
        { text: "「頑張った」で終わる日は、よく使った一日。", author: "MiniStep" },
        { text: "朝の光に、肌だけでなく心も温めてもらおう。", author: "MiniStep" },
        { text: "今夜、今日完璧じゃなかった自分を許そう。", author: "MiniStep" },
        { text: "朝のお茶やコーヒーは小さな儀式。そのように扱おう。", author: "MiniStep" },
        { text: "毎夕、手放す練習をしよう。", author: "MiniStep" },
        { text: "毎朝の最初の一息は、小さな奇跡。", author: "MiniStep" },
        { text: "できることをしたと知りながら今日を終えよう。したいことをしながら明日を始めよう。", author: "MiniStep" },
        { text: "夜の静けさの中で、明日の勇気が静かに育つ。", author: "MiniStep" },
        { text: "一日に飛び込む前に聞いてみよう：今一番大切なことは何？", author: "MiniStep" },
        { text: "夜は解放のため。明日の心配をリハーサルするためじゃない。", author: "MiniStep" },
        { text: "すべての日の出が静かに言う：もう一度チャンスがある。", author: "MiniStep" },

        // --- 人間関係とつながり (201-240) ---
        { text: "心からの「元気？」が、誰かの一日を変えることがある。", author: "MiniStep" },
        { text: "大切な人はあなたの完璧を求めていない。ただあなたの存在を求めている。", author: "MiniStep" },
        { text: "ただ聞くことが、最大の愛の行為になることがある。", author: "MiniStep" },
        { text: "小さなメッセージが、長い沈黙に橋をかけることができる。", author: "MiniStep" },
        { text: "優しさはコストゼロ。でも意味は無限大。", author: "MiniStep" },
        { text: "いつも忘れてしまう人に感謝しよう。", author: "MiniStep" },
        { text: "弱さをさらけ出すことは弱さじゃない。つながりの生まれる場所だ。", author: "MiniStep" },
        { text: "今日、誰かのために現れよう。どんなに小さな方法でも。", author: "MiniStep" },
        { text: "本物の褒め言葉に賞味期限はない。今日一つ贈ろう。", author: "MiniStep" },
        { text: "最高の会話は好奇心から始まる。アドバイスからじゃない。", author: "MiniStep" },
        { text: "人はあなたが何を言ったかより、どう感じさせてくれたかを覚えている。", author: "MiniStep" },
        { text: "知らない人への微笑みはコストゼロ。でもすべてを意味するかもしれない。", author: "MiniStep" },
        { text: "頭の中で作ってきたメッセージを送ろう。", author: "MiniStep" },
        { text: "人の問題を解決しなくていい。ただそこにいることを伝えよう。", author: "MiniStep" },
        { text: "感謝の小さな行動が積み重なって、深い関係になる。", author: "MiniStep" },
        { text: "優しいことを声に出して言おう。人はあなたの心を読めない。", author: "MiniStep" },
        { text: "つながりに言葉は必要ない。存在するだけで十分なときもある。", author: "MiniStep" },
        { text: "許すことは相手だけでなく、自分自身への贈り物。", author: "MiniStep" },
        { text: "頼まれなくても気にかける人が、世界にはもっと必要だ。", author: "MiniStep" },
        { text: "質の高い時間は長くなくていい。正直な5分で十分なことがある。", author: "MiniStep" },
        { text: "信頼できる人との共有された沈黙は、それ自体が会話だ。", author: "MiniStep" },
        { text: "すべての友情は、かつて二人の見知らぬ人が挨拶したところから始まった。", author: "MiniStep" },
        { text: "何も修正しようとせず、今日は誰かのための空間を持とう。", author: "MiniStep" },
        { text: "必要だからじゃなく、したいから誰かに連絡しよう。", author: "MiniStep" },
        { text: "あなたの人たちはあなたの完璧を必要としていない。ただ存在することを必要としている。", author: "MiniStep" },
        { text: "優しい言葉は種のようなもの。それが育つ木を見ることはないかもしれない。", author: "MiniStep" },
        { text: "見えない重荷を背負っている人がいる。優しくしよう。", author: "MiniStep" },
        { text: "声に出して分かち合う感謝は、その力が2倍になる。", author: "MiniStep" },
        { text: "最高の関係は、普通の瞬間の中で作られる。", author: "MiniStep" },
        { text: "今日誰かに「あなたに感謝している」と言おう。何が起きるか見てみよう。", author: "MiniStep" },
        { text: "本当に聞いてもらえることは、与えられる最高の贈り物の一つ。", author: "MiniStep" },
        { text: "小さな思いやりの行動が、意味のある関係の接着剤だ。", author: "MiniStep" },
        { text: "今日は、あなたが苦しんでいたときに必要だった人になろう。", author: "MiniStep" },
        { text: "誰かの痛みを理解しなくても、それについて優しくすることはできる。", author: "MiniStep" },
        { text: "今日、誰かの小さな勝利を祝おう。それが唯一のお祝いかもしれない。", author: "MiniStep" },
        { text: "すべての関係に言葉が必要なわけじゃない。時間が必要なものもある。", author: "MiniStep" },
        { text: "一回の正直な会話が、百の思い込みに取って代わることができる。", author: "MiniStep" },
        { text: "今日あなたのことを考えたよ、と誰かに伝えよう。それだけで十分。", author: "MiniStep" },
        { text: "愛は多くの場合、最も小さく見過ごされた行動の中に見つかる。", author: "MiniStep" },
        { text: "二つの心の間の最もシンプルな橋は、気にかけていることを示すこと。", author: "MiniStep" },

        // --- 習慣とシステム (241-280) ---
        { text: "習慣は、なりたい自分への投票だ。", author: "MiniStep" },
        { text: "良いことを簡単に。悪いことを難しく。", author: "MiniStep" },
        { text: "アイデンティティの変化は「私は〇〇する人間」から始まる。", author: "MiniStep" },
        { text: "新しい習慣を既存の習慣につなげよう。それが魔法の公式。", author: "MiniStep" },
        { text: "目標のレベルには上がれない。システムのレベルに落ちる。", author: "MiniStep" },
        { text: "2分ルール：2分以内で終わるなら、今すぐやろう。", author: "MiniStep" },
        { text: "正しい選択がデフォルトになるように環境を設計しよう。", author: "MiniStep" },
        { text: "完璧のためでなく、気づきのために進歩を追跡しよう。", author: "MiniStep" },
        { text: "1回サボるのは事故。2回連続は新しい習慣の始まり。", author: "MiniStep" },
        { text: "2回連続でサボらない。必要なルールはそれだけ。", author: "MiniStep" },
        { text: "しなければいけないことと、大好きなことをペアにしよう。", author: "MiniStep" },
        { text: "環境は意志力よりもあなたの行動を形作る。", author: "MiniStep" },
        { text: "ほとんど馬鹿らしいくらい小さく始めよう。それが正しいサイズ。", author: "MiniStep" },
        { text: "良い習慣のある悪いシステムでも、システムがないよりまし。", author: "MiniStep" },
        { text: "小さな習慣の後に毎回お祝いしよう。脳は報酬シグナルが必要。", author: "MiniStep" },
        { text: "習慣は自己改善の複利だ。", author: "MiniStep" },
        { text: "最高の習慣は、実際にやる習慣。", author: "MiniStep" },
        { text: "早すぎる最適化はしない。まず継続することだけを。", author: "MiniStep" },
        { text: "繰り返しはスキルの母で、習慣の父だ。", author: "MiniStep" },
        { text: "決断を自動化しよう。行動は自然についてくる。", author: "MiniStep" },
        { text: "毎日の1分の習慣は、1回だけの60分の習慣に勝る。", author: "MiniStep" },
        { text: "ルーティンは儀式だ。尊重して扱おう。", author: "MiniStep" },
        { text: "小さな成功のチェーンを作ろう。そのチェーンがあなたのアイデンティティになる。", author: "MiniStep" },
        { text: "摩擦は習慣の敵。摩擦を取り除けば、流れるようにできる。", author: "MiniStep" },
        { text: "すぐに自分にご褒美をあげよう。遅延した報酬は習慣を作らない。", author: "MiniStep" },
        { text: "目標よりシステム。目標は方向を示し、システムは進歩を決める。", author: "MiniStep" },
        { text: "毎日のデフォルトが、長期的な運命を作る。", author: "MiniStep" },
        { text: "スケジュールに入れたことが実行される。小さな習慣をカレンダーに。", author: "MiniStep" },
        { text: "今は結果を忘れよう。プロセスを好きになろう。", author: "MiniStep" },
        { text: "持続的な変化の秘訣：明白に、魅力的に、簡単に、満足できるように。", author: "MiniStep" },
        { text: "良いシステムは、正しいことをすることを最も抵抗の少ない道にする。", author: "MiniStep" },
        { text: "習慣を積み木のように積み上げよう。一つひとつが次をサポートする。", author: "MiniStep" },
        { text: "未来の自分は、今の自分が選ぶルーティンで作られる。", author: "MiniStep" },
        { text: "アカウンタビリティは罰じゃない。正直でいるのを助ける鏡だ。", author: "MiniStep" },
        { text: "人生を変える最も簡単な方法は、デフォルトを変えること。", author: "MiniStep" },
        { text: "小さな儀式が、混沌とした日の大きな錨になる。", author: "MiniStep" },
        { text: "新しい習慣を加える前に聞いてみよう：代わりに何を取り除ける？", author: "MiniStep" },
        { text: "継続は静かだが、その結果は大きい。", author: "MiniStep" },
        { text: "朝のルーティンは、毎日自分との約束を守ること。", author: "MiniStep" },
        { text: "続く習慣は、あなたの生活に合ったもの。逆じゃない。", author: "MiniStep" },

        // --- 勇気と回復力 (281-320) ---
        { text: "勇気は恐れがないことじゃない。恐れながらも一歩踏み出すこと。", author: "MiniStep" },
        { text: "すべてのカムバック物語は、倒れたままでいないと決めた人から始まった。", author: "MiniStep" },
        { text: "あなたは以前にも自分を再生させた。またできる。", author: "MiniStep" },
        { text: "失敗に見えるものは多くの場合、成功の下書きにすぎない。", author: "MiniStep" },
        { text: "成長はあなたのコンフォートゾーンのすぐ外側に生きている。", author: "MiniStep" },
        { text: "あなたは自分が思うより勇敢で、見た目より強い。", author: "MiniStep" },
        { text: "自信への道は、ぎこちない初挑戦で舗装されている。", author: "MiniStep" },
        { text: "今日の不快感が、明日の「あの頃はできなかったけどね」になる。", author: "MiniStep" },
        { text: "恐れは新しい何かの境界線にいるサイン。踏み越えよう。", author: "MiniStep" },
        { text: "最初はいつも一番難しい。二回目はもう少し楽。", author: "MiniStep" },
        { text: "後退は変装したセットアップだ。", author: "MiniStep" },
        { text: "回復力は決して倒れないことじゃない。もう一度立ち上がること。", author: "MiniStep" },
        { text: "あなたは脆くない。逆境で強くなるタイプ。困難があなたを強くする。", author: "MiniStep" },
        { text: "割れ目から光が入る。", author: "MiniStep" },
        { text: "まず下手くそにやることを恐れるな。熟練は繰り返しから来る。", author: "MiniStep" },
        { text: "恐れ知らずになる必要はない。毎日少しだけ、恐れを小さくしよう。", author: "MiniStep" },
        { text: "不快感はデータだ。成長しているということを教えてくれる。", author: "MiniStep" },
        { text: "過去の失敗は訓練であり、運命ではない。", author: "MiniStep" },
        { text: "続けよう。ぶつかっている壁は、もうすぐ開くドアかもしれない。", author: "MiniStep" },
        { text: "すべての傷跡は、癒えたことの証拠。", author: "MiniStep" },
        { text: "夜明け前が一番暗い。でも夜明けは必ずやってくる。", author: "MiniStep" },
        { text: "早く失敗することは早く学ぶこと。つまずくことを恐れるな。", author: "MiniStep" },
        { text: "勇気とは、怖くてもやること。", author: "MiniStep" },
        { text: "あなたは辛いことを乗り越えられることをすでに証明している。", author: "MiniStep" },
        { text: "一つの勇敢な瞬間が、すべての方向を変えることができる。", author: "MiniStep" },
        { text: "弱い日でも、あなたの強さは消えていない。ただ休んでいるだけ。", author: "MiniStep" },
        { text: "やめたくなったとき、なぜ始めたか思い出そう。", author: "MiniStep" },
        { text: "自分に忍耐強くなろう。大きなことは小さな、着実な努力から生まれる。", author: "MiniStep" },
        { text: "荒れたスタートは、荒れたゴールを意味しない。", author: "MiniStep" },
        { text: "出口は通り抜けることだけ。でもゆっくり通り抜けていい。", author: "MiniStep" },
        { text: "あなたはできないと思っていたことを乗り越えてきた。これも乗り越えられる。", author: "MiniStep" },
        { text: "傷跡はどこにいたかを教えてくれる。どこに行くかではない。", author: "MiniStep" },
        { text: "底は発射台にもなれる。そう決めれば。", author: "MiniStep" },
        { text: "最も強い人は、弱さを感じた後も試み続ける人。", author: "MiniStep" },
        { text: "勇敢であるために吠える必要はない。「やってみる」というつぶやきで十分。", author: "MiniStep" },
        { text: "嵐は過ぎる。いつも。そしてあなたはまだここにいる。", author: "MiniStep" },
        { text: "弱さを見せることは、意味のある成長への入場料だ。", author: "MiniStep" },
        { text: "すべての「できない」の裏には、隠れた「まだやっていない」がある。", author: "MiniStep" },
        { text: "あなたはどんな一日の悪さよりも強い。", author: "MiniStep" },
        { text: "回復力は決して壊れないことで測られるんじゃない。常に修復することで測られる。", author: "MiniStep" },

        // --- シンプルさとマインドフルネス (321-360) ---
        { text: "少なくするけど、全ての注意を注いでやろう。", author: "MiniStep" },
        { text: "本質だけが残るまでシンプルにしよう。", author: "MiniStep" },
        { text: "今この瞬間が、あなたが実際に持っている唯一の瞬間。", author: "MiniStep" },
        { text: "普段素通りするような美しいものを、今日は一つ気づいてみよう。", author: "MiniStep" },
        { text: "忙しさは進歩と同じじゃない。", author: "MiniStep" },
        { text: "心は庭だ。何を植えるか慎重に選ぼう。", author: "MiniStep" },
        { text: "今日は、10個を同時にこなす代わりに、一つずつやってみよう。", author: "MiniStep" },
        { text: "最も力強い言葉は「ノー」。エネルギーを守るために使おう。", author: "MiniStep" },
        { text: "明確さは足し算ではなく、引き算から来る。", author: "MiniStep" },
        { text: "足のある場所にいよう。", author: "MiniStep" },
        { text: "急ぐことは早く着くことじゃない。むしろ多くを逃すことがある。", author: "MiniStep" },
        { text: "散らかった空間は、散らかった心を反映することが多い。一角を片付けよう。", author: "MiniStep" },
        { text: "注意のドアをノックするすべてに答える必要はない。", author: "MiniStep" },
        { text: "立ち止まることは止まることじゃない。力を集めることだ。", author: "MiniStep" },
        { text: "五つを中途半端にするより、一つを徹底的にする方が力がある。", author: "MiniStep" },
        { text: "思考の合間の静寂に耳を傾けよう。そこに平和が宿る。", author: "MiniStep" },
        { text: "今日をシンプルにしよう。次に正しいことをするだけでいい。", author: "MiniStep" },
        { text: "スマホは待てる。この瞬間は待てない。", author: "MiniStep" },
        { text: "普通の瞬間を味わおう。あなたが思うより希少だ。", author: "MiniStep" },
        { text: "考えすぎは、まだ存在しない問題を作り出すアートだ。", author: "MiniStep" },
        { text: "4で吸って、4で止めて、4で吐く。自分に贈り物をした。", author: "MiniStep" },
        { text: "十分は決断であり、目的地ではない。", author: "MiniStep" },
        { text: "すべてが緊急に感じるとき、実は何も緊急じゃない。立ち止まって優先順位をつけよう。", author: "MiniStep" },
        { text: "目的地のない散歩も、取る価値のある散歩だ。", author: "MiniStep" },
        { text: "静けさは怠惰じゃない。最高のアイデアが住んでいる場所。", author: "MiniStep" },
        { text: "あなたはToDoリストじゃない。", author: "MiniStep" },
        { text: "一回の意識的な呼吸が、現在に連れ戻してくれる。", author: "MiniStep" },
        { text: "注意の質は、努力の量より重要。", author: "MiniStep" },
        { text: "平和はもっと持つことで見つかるんじゃない。必要とするものが少なくなることで。", author: "MiniStep" },
        { text: "今日は、速さより深さを選ぼう。", author: "MiniStep" },
        { text: "最も忙しい人が、しばしば最も静けさを必要としている。", author: "MiniStep" },
        { text: "集中した1時間は、散漫な3時間を上回る。", author: "MiniStep" },
        { text: "輝くものすべてがあなたの注意に値するわけじゃない。", author: "MiniStep" },
        { text: "今できる最も生産的なことは、止まることかもしれない。", author: "MiniStep" },
        { text: "シンプルさは日常生活における究極の洗練。", author: "MiniStep" },
        { text: "刺激と反応の間の空間に気づいて。そこに自由が宿る。", author: "MiniStep" },
        { text: "静かな心は、忙しい心より多くを聞く。", author: "MiniStep" },
        { text: "人生で最も重要なものはモノじゃない。", author: "MiniStep" },
        { text: "騒音を消そう。残るものが大切なもの。", author: "MiniStep" },
        { text: "もっと時間が必要なんじゃない。もっと存在が必要。", author: "MiniStep" },

        // --- 喜びと感謝 (361-400) ---
        { text: "喜びはゴールラインにあるんじゃない。途中の一歩一歩にある。", author: "MiniStep" },
        { text: "感謝は持っているものを十分に変える。", author: "MiniStep" },
        { text: "今日、微笑めることを一つ見つけよう。どんなに小さくても。", author: "MiniStep" },
        { text: "幸せはよく平凡な中に隠れている。もっとよく見よう。", author: "MiniStep" },
        { text: "小さな勝利を祝おう。それがあなたを作り上げていく。", author: "MiniStep" },
        { text: "温かい飲み物、静かな隅、深い息。贅沢はコストゼロ。", author: "MiniStep" },
        { text: "今日には良いものが入っている。ただ探せばいい。", author: "MiniStep" },
        { text: "今日何かに笑おう。体がそれを必要としている。", author: "MiniStep" },
        { text: "毎日繰り返す小さな喜びが、幸せな人生の基盤。", author: "MiniStep" },
        { text: "今日何があなたを笑顔にした？それを大切に持っていよう。", author: "MiniStep" },
        { text: "幸せは目的地じゃない。小さな瞬間の集まりだ。", author: "MiniStep" },
        { text: "肌に当たる日光の温かさに気づいて。それは贈り物。", author: "MiniStep" },
        { text: "キッチンで踊ることは、運動でもあり喜びでもある。", author: "MiniStep" },
        { text: "好きな曲はいつもタップ一つの先にある。今流そう。", author: "MiniStep" },
        { text: "小さなこと？実は小さくない。", author: "MiniStep" },
        { text: "今日は、完了することに喜びを見つけよう。小さなことでも。", author: "MiniStep" },
        { text: "良い一日は大きな一日じゃなくていい。", author: "MiniStep" },
        { text: "モノではなく、瞬間を集めよう。", author: "MiniStep" },
        { text: "雨の匂い、友人の笑い声、満タンのバッテリー。人生の隠れた宝物。", author: "MiniStep" },
        { text: "大きなことを待たずに、小さなことを楽しむ価値がある。", author: "MiniStep" },
        { text: "今日良いことが一つあれば、今日を良い日と呼ぶのに十分。", author: "MiniStep" },
        { text: "今日は心を軽くしよう。あなたはそれに値する。", author: "MiniStep" },
        { text: "毎日少なくとも一つの小さな奇跡がある。あなたの仕事はそれに気づくこと。", author: "MiniStep" },
        { text: "日光が見つからないなら、あなたが日光になろう。", author: "MiniStep" },
        { text: "喜ぶことはスキルだ。練習しよう。", author: "MiniStep" },
        { text: "今、何に感謝している？名前をつけよう。感じよう。", author: "MiniStep" },
        { text: "満ちた心は、満ちたスケジュールを必要としない。", author: "MiniStep" },
        { text: "人生で最高のものは無料。そして大抵小さい。", author: "MiniStep" },
        { text: "今日まで来た。それはお祝いに値する。", author: "MiniStep" },
        { text: "この日を終えよう。ここにいた、頑張った、それが大事だと知りながら。", author: "MiniStep" },
        { text: "追いかけるのをやめて気づき始めたとき、喜びが忍び込んでくる。", author: "MiniStep" },
        { text: "あなたの笑いは薬。毎日服用しよう。", author: "MiniStep" },
        { text: "感謝は無料のセラピー。今すぐセッションを予約しよう。", author: "MiniStep" },
        { text: "小さな喜びを探そう：良いペン、温かいブランケット、完璧な一口。", author: "MiniStep" },
        { text: "世界のどこかで、あなたの普通の火曜日を羨む人がいる。", author: "MiniStep" },
        { text: "今日、何かに喜ばせてもらおう。その許可を自分に与えよう。", author: "MiniStep" },
        { text: "最も幸せな人は最も幸運なのではなく、最も感謝している人。", author: "MiniStep" },
        { text: "今日見た美しいものを3つ挙げよう。美しさはいつも近くにある。", author: "MiniStep" },
        { text: "感謝で満ちた心に、不平の余地はない。", author: "MiniStep" },
        { text: "今日の喜びは勝ち取る必要はない。もうここにある、気づかれるのを待っている。", author: "MiniStep" }
    ],

    // ========= Challenges (720: 120 per category × 6) =========
    challenges: [
        // ╔══════════════════════════════════╗
        // ║  outside — 120 challenges        ║
        // ╚══════════════════════════════════╝
        { text: "コンビニやスーパーへ、いつもと違う道を通って行ってみよう", category: "outside", difficulty: 1 },
        { text: "外に出て空を見上げ、深呼吸を3回しよう", category: "outside", difficulty: 1 },
        { text: "近所で少し気になっていた場所を一か所訪れてみよう", category: "outside", difficulty: 2 },
        { text: "家の周りを5分歩いて、目に留まるものを一つ見つけよう", category: "outside", difficulty: 1 },
        { text: "最寄り駅へ向かう途中、いつも通らないお店の前を通ってみよう", category: "outside", difficulty: 1 },
        { text: "外に出て、季節を感じるものを一枚撮ってみよう", category: "outside", difficulty: 2 },
        { text: "エレベーターの代わりに、一階分だけ階段を使ってみよう", category: "outside", difficulty: 1 },
        { text: "近くの公園や広場へ行き、ベンチにたった1分座ってみよう", category: "outside", difficulty: 1 },
        { text: "玄関の外に出て、空を一枚撮ってみよう", category: "outside", difficulty: 1 },
        { text: "家から見える一番近い場所まで歩き、「今日はここまで」と決めて引き返そう", category: "outside", difficulty: 1 },
        { text: "近くの自販機かコンビニまで歩き、ご褒美ドリンクを一本選ぼう", category: "outside", difficulty: 2 },
        { text: "普段行かないフロアにエレベーターで行き、30秒間きょろきょろしてみよう", category: "outside", difficulty: 2 },
        { text: "スマホを見ずに、ブロックを一周歩いてみよう", category: "outside", difficulty: 1 },
        { text: "家の近くの木を見つけ、30秒じっくり観察してみよう", category: "outside", difficulty: 1 },
        { text: "外に出て、目に見える5つの違う色を数えてみよう", category: "outside", difficulty: 1 },
        { text: "最寄りのポストか郵便局まで歩こう——それが今日のゴール", category: "outside", difficulty: 1 },
        { text: "近くのカフェやパン屋へ行き、10秒間香りを楽しもう", category: "outside", difficulty: 1 },
        { text: "日当たりのいい場所を見つけ、1分間日光を浴びよう", category: "outside", difficulty: 1 },
        { text: "どこかを歩きながら、何羽の鳥を見つけられるか数えてみよう", category: "outside", difficulty: 1 },
        { text: "家の近くで育っている緑のものを一枚撮ってみよう", category: "outside", difficulty: 1 },
        { text: "いつもと違う時間帯に外へ出てみよう", category: "outside", difficulty: 2 },
        { text: "最寄りの水辺——川・池・噴水・水道まで歩いてみよう", category: "outside", difficulty: 2 },
        { text: "近所で今まで気づかなかった花や植物を見つけてみよう", category: "outside", difficulty: 1 },
        { text: "外のどこかに座って、30秒目を閉じよう——ただ聴くだけでいい", category: "outside", difficulty: 1 },
        { text: "安全な地面の上で、10秒だけ裸足で外に出てみよう", category: "outside", difficulty: 1 },
        { text: "通りの端まで歩いて、そこからの景色を眺めよう", category: "outside", difficulty: 1 },
        { text: "3分間歩きながら、空気が肌にどう感じるか意識してみよう", category: "outside", difficulty: 1 },
        { text: "一番近い公園や広場へ行き、しばらくそこに立っていよう", category: "outside", difficulty: 1 },
        { text: "外に出て、美しいと思うものを見つけよう——何でもOK", category: "outside", difficulty: 1 },
        { text: "近くのお店まで歩き、何も買わずウィンドウショッピングを楽しもう", category: "outside", difficulty: 1 },
        { text: "いつもと違う出口から建物を出てみよう", category: "outside", difficulty: 1 },
        { text: "5分圏内で一番古そうな建物を見つけて撮影しよう", category: "outside", difficulty: 2 },
        { text: "歩きながらちょうど100歩数えたら止まり、周りを見回してみよう", category: "outside", difficulty: 1 },
        { text: "今日の散歩でゴミを一つ拾おう", category: "outside", difficulty: 1 },
        { text: "新しい場所を歩いて、普段聞かない音を3つ見つけよう", category: "outside", difficulty: 1 },
        { text: "外に出て、今の気分と同じ色のものを見つけよう", category: "outside", difficulty: 1 },
        { text: "近所で前を通り過ぎたことはあるけれど入ったことのない小さなお店へ行こう", category: "outside", difficulty: 2 },
        { text: "今夜は夕食後に少し散歩しよう", category: "outside", difficulty: 1 },
        { text: "今まで座ったことのない新しいベンチや縁石、スポットを見つけよう", category: "outside", difficulty: 1 },
        { text: "最寄りの橋・高架・高い場所まで歩き、景色を楽しもう", category: "outside", difficulty: 2 },
        { text: "外に出て風の向きを感じよう。どちらから吹いている？", category: "outside", difficulty: 1 },
        { text: "散歩しながら、目線より上にあるものだけを見てみよう", category: "outside", difficulty: 1 },
        { text: "最寄りの信号まで歩き、一回分のサイクルを待ってみよう", category: "outside", difficulty: 1 },
        { text: "10秒間、車の音が聞こえない野外スポットを見つけよう", category: "outside", difficulty: 2 },
        { text: "一方向に5分だけ歩き、そのまま引き返そう", category: "outside", difficulty: 1 },
        { text: "短い散歩で、犬（または猫）を何匹見かけるか数えよう", category: "outside", difficulty: 1 },
        { text: "外で心が落ち着くものを見つけ、撮影しよう", category: "outside", difficulty: 1 },
        { text: "今すぐ外へ出よう——60秒でもいい", category: "outside", difficulty: 1 },
        { text: "近くの寺社・教会・地域施設まで歩き、掲示板を読もう", category: "outside", difficulty: 2 },
        { text: "一度も歩いたことのない通りを遠回りして通ってみよう", category: "outside", difficulty: 2 },
        { text: "家の近くで一番高い木を見つけ、しばらくその下に立とう", category: "outside", difficulty: 1 },
        { text: "目的地を決めずに歩き出し、好奇心に任せて進もう", category: "outside", difficulty: 2 },
        { text: "夕暮れか夜明けに外へ出て、2分間眺めよう", category: "outside", difficulty: 2 },
        { text: "傘を差して雨の中を散歩しよう——音に耳を澄まして", category: "outside", difficulty: 2 },
        { text: "最寄りの書店・図書館・雑誌コーナーへ行き、3分間ぶらりと見て回ろう", category: "outside", difficulty: 2 },
        { text: "ちょうど500歩先の場所まで歩こう", category: "outside", difficulty: 1 },
        { text: "外に出て、虫・鳥・小動物を見つけて観察しよう", category: "outside", difficulty: 1 },
        { text: "よく響く場所を見つけ、「こんにちは」と声をかけてみよう", category: "outside", difficulty: 1 },
        { text: "近くの案内板や地図まで歩き、知らなかったことを一つ読もう", category: "outside", difficulty: 2 },
        { text: "外に出て、30秒間肌に感じる温度を意識してみよう", category: "outside", difficulty: 1 },
        { text: "散歩しながら、最寄りの公園まで何歩かかるか数えよう", category: "outside", difficulty: 1 },
        { text: "外に出て、自分の影を撮影しよう", category: "outside", difficulty: 1 },
        { text: "歩きながら、少なくとも一人に挨拶しよう", category: "outside", difficulty: 2 },
        { text: "地平線（または水平線）が見える場所を探し、ただ眺めよう", category: "outside", difficulty: 2 },
        { text: "2分間、呼吸だけに意識を向けながら歩こう", category: "outside", difficulty: 1 },
        { text: "いつもと違うコンビニへ行ってみよう", category: "outside", difficulty: 1 },
        { text: "外に出て、丸・四角・三角のものをそれぞれ見つけよう", category: "outside", difficulty: 1 },
        { text: "今日は目的地まで遠回りしよう——近道は使わない", category: "outside", difficulty: 2 },
        { text: "最寄りの横断歩道まで歩き、左・右・渡ると意識して渡ろう", category: "outside", difficulty: 1 },
        { text: "公共の場へ行き、スマホなしで2分間人間観察をしよう", category: "outside", difficulty: 2 },
        { text: "芝生や草地を見つけ、30秒間立ってみよう", category: "outside", difficulty: 1 },
        { text: "川・湖・噴水・水たまりなど、最寄りの水辺へ行って眺めよう", category: "outside", difficulty: 2 },
        { text: "いつもの半分のスピードで3分間歩き、何が見えるか気づこう", category: "outside", difficulty: 1 },
        { text: "外に出て、3種類の雲を見分けてみよう", category: "outside", difficulty: 1 },
        { text: "今夜、月が見える外のスポットを探そう", category: "outside", difficulty: 1 },
        { text: "意識して景色のいい道を選んで歩こう", category: "outside", difficulty: 2 },
        { text: "外に出て、樹皮・金属・石・葉など5種類の質感に触れよう", category: "outside", difficulty: 1 },
        { text: "地域の掲示板を訪れ、お知らせを一つ読もう", category: "outside", difficulty: 1 },
        { text: "歩ける範囲で一番面白いドアを見つけて撮影しよう", category: "outside", difficulty: 2 },
        { text: "気になるものを見つけるまで歩き、そこで立ち止まろう", category: "outside", difficulty: 1 },
        { text: "近くの屋上・丘・高台へ行き、景色を楽しもう", category: "outside", difficulty: 2 },
        { text: "いつも素通りするお店の一区画を探検してみよう", category: "outside", difficulty: 1 },
        { text: "歩きながら、目に入る赤いものをすべて数えよう", category: "outside", difficulty: 1 },
        { text: "外に出て空を見上げ、一言で表してみよう", category: "outside", difficulty: 1 },
        { text: "家の近くでストリートアート・グラフィティ・壁画を探そう", category: "outside", difficulty: 2 },
        { text: "今日は1,000歩歩こう——スマホで計測してもOK", category: "outside", difficulty: 2 },
        { text: "外に出て、空気中の3つの匂いを感じ取ろう", category: "outside", difficulty: 1 },
        { text: "近くの公園へ行き、一番面白い形の木を見つけよう", category: "outside", difficulty: 1 },
        { text: "散歩しながら誰かに手を振ろう——少し照れくさくてもOK", category: "outside", difficulty: 2 },
        { text: "外に出て地面を見よう。面白い質感や模様を一つ探そう", category: "outside", difficulty: 1 },
        { text: "最も遠くを見渡せる場所まで歩き、どこまで見えるか確かめよう", category: "outside", difficulty: 2 },
        { text: "散歩のついでに小さなご褒美を一つ買おう——自分へのご褒美", category: "outside", difficulty: 1 },
        { text: "外で2分間座り、ただ周りの動きを眺めよう", category: "outside", difficulty: 1 },
        { text: "観光客として初めてこの場所を訪れたつもりで歩いてみよう", category: "outside", difficulty: 2 },
        { text: "外に出て確かめよう——今日の空気は涼しい？暖かい？湿気がある？乾いている？", category: "outside", difficulty: 1 },
        { text: "昔よく行っていたのに最近行っていない場所まで歩こう", category: "outside", difficulty: 2 },
        { text: "外に出て、聞こえる中で一番遠くの音を聴いてみよう", category: "outside", difficulty: 1 },
        { text: "地面に映る光の輪を見つけ、その中に立ってみよう", category: "outside", difficulty: 1 },
        { text: "お気に入りの近所スポットへ歩き、なぜ好きかを1分間かみしめよう", category: "outside", difficulty: 1 },
        { text: "いつも前を通るのに曲がったことのない路地を探索しよう", category: "outside", difficulty: 2 },
        { text: "外に出て、今日一番深い深呼吸をしよう", category: "outside", difficulty: 1 },
        { text: "最寄りの階段まで歩き、登って——頂上からの眺めを楽しもう", category: "outside", difficulty: 1 },
        { text: "5分以内に行ける一番静かな野外スポットを探そう", category: "outside", difficulty: 2 },
        { text: "近くの公園へ行き、道の代わりに芝生の上を歩こう", category: "outside", difficulty: 1 },
        { text: "外に出て、これまで気づかなかったものを3つ見つけよう", category: "outside", difficulty: 1 },
        { text: "お店まで歩き、小さなものを買い、笑顔で「ありがとう」を伝えよう", category: "outside", difficulty: 1 },
        { text: "外で、幸せな思い出を呼び起こすものを見つけよう", category: "outside", difficulty: 1 },
        { text: "10分間散歩しよう——MiniStep史上最長の冒険", category: "outside", difficulty: 2 },
        { text: "外に出て自然光の中で自撮りしよう。自分だけの記念に", category: "outside", difficulty: 1 },
        { text: "バス停・駅・タクシー乗り場まで歩き、どこへ行くか想像してみよう", category: "outside", difficulty: 1 },
        { text: "地面の葉っぱを拾い上げ、細部をじっくり観察しよう", category: "outside", difficulty: 1 },
        { text: "歩きながら、ちょうど200歩になるまで数えよう", category: "outside", difficulty: 1 },

        // ╔══════════════════════════════════╗
        // ║  communication — 120 challenges   ║
        // ╚══════════════════════════════════╝
        { text: "職場や学校で、いつもより丁寧に挨拶してみよう", category: "communication", difficulty: 1 },
        { text: "最近連絡していない友人にメッセージを送ろう——スタンプ一つでもいい", category: "communication", difficulty: 2 },
        { text: "店員さんや配達員さんに、いつもより心を込めてお礼を伝えよう", category: "communication", difficulty: 2 },
        { text: "今日感謝した瞬間を一つ思い出し、心の中でもう一度お礼を言おう", category: "communication", difficulty: 1 },
        { text: "SNSで誰かの投稿にいいねするか、短いポジティブなコメントを残そう", category: "communication", difficulty: 2 },
        { text: "今日、身近な人の良いところを一つ見つけよう", category: "communication", difficulty: 1 },
        { text: "苦しんでいる人に気づいたら、心の中でそっと応援しよう", category: "communication", difficulty: 1 },
        { text: "家族や同居人に「今日もお疲れさま」と声をかけよう", category: "communication", difficulty: 1 },
        { text: "今日が終わるまでに感謝を伝えられる人を一人思い浮かべよう", category: "communication", difficulty: 1 },
        { text: "最近助けてくれた人に、3行以内のお礼メッセージを送ろう", category: "communication", difficulty: 2 },
        { text: "オンラインでもオフラインでも、誰かの良いところを一つ静かに認めよう", category: "communication", difficulty: 1 },
        { text: "気になっていたSNSアカウントをフォローし、投稿を一つ読もう", category: "communication", difficulty: 2 },
        { text: "笑いを必要としている人に面白いミームや動画を送ろう", category: "communication", difficulty: 1 },
        { text: "誰かに「今日どうだった？」と聞き、答えをしっかり聞こう", category: "communication", difficulty: 2 },
        { text: "誰かの具体的なもの——仕事・センス・努力を褒めよう", category: "communication", difficulty: 2 },
        { text: "未読のままにしていたメッセージに返信しよう", category: "communication", difficulty: 2 },
        { text: "誰かに、その人のどこがありがたいかを伝えよう——さりげなくてもいい", category: "communication", difficulty: 2 },
        { text: "今日3人に笑顔を向けよう——知らない人でもOK", category: "communication", difficulty: 1 },
        { text: "同僚やクラスメートに、その人の興味のあることを聞いてみよう", category: "communication", difficulty: 2 },
        { text: "楽しんでくれそうな人に、曲・記事・写真をシェアしよう", category: "communication", difficulty: 1 },
        { text: "いつも挨拶しない人に「おはようございます」と言ってみよう", category: "communication", difficulty: 1 },
        { text: "短い励ましのメモを書き、誰かが見つけられる場所に置こう", category: "communication", difficulty: 2 },
        { text: "誰かにおすすめを聞こう——レストラン・本・番組など", category: "communication", difficulty: 2 },
        { text: "友達に話しかけるように、自分に声に出して優しい言葉をかけよう", category: "communication", difficulty: 1 },
        { text: "誰かのためにドアを押さえるか、小さな手助けを申し出よう", category: "communication", difficulty: 1 },
        { text: "今日はテキストの代わりに、誰かに音声メッセージを送ろう", category: "communication", difficulty: 2 },
        { text: "会話の中で相手と目を合わせ、うなずいてみよう", category: "communication", difficulty: 1 },
        { text: "今日あった小さな成果を誰かに話そう", category: "communication", difficulty: 2 },
        { text: "誰かに「今週一番よかったことは何？」と聞いてみよう", category: "communication", difficulty: 2 },
        { text: "「今日あなたのこと思い出した」とメッセージを送ろう——それだけでいい", category: "communication", difficulty: 1 },
        { text: "気に入ったお店・レストラン・サービスにポジティブなレビューを残そう", category: "communication", difficulty: 2 },
        { text: "今日学んだことを一つ誰かに話そう", category: "communication", difficulty: 1 },
        { text: "新しい人に自己紹介しよう——「こんにちは」だけでもいい", category: "communication", difficulty: 2 },
        { text: "家族に子供の頃の思い出を聞いてみよう", category: "communication", difficulty: 2 },
        { text: "SNSの誰かのストーリーに、素直な反応を送ろう", category: "communication", difficulty: 1 },
        { text: "今日はメッセージではなく電話してみよう", category: "communication", difficulty: 2 },
        { text: "見た目ではなく、性格について予想外の褒め言葉を伝えよう", category: "communication", difficulty: 2 },
        { text: "「楽しみにしていることは何？」と聞き、しっかり耳を傾けよう", category: "communication", difficulty: 2 },
        { text: "身近な人に子供の頃の思い出を話そう", category: "communication", difficulty: 2 },
        { text: "名札が見えたら、スタッフさんの名前を呼んでお礼を言おう", category: "communication", difficulty: 2 },
        { text: "「いい一日でありますように」と友人にメッセージを送ろう", category: "communication", difficulty: 1 },
        { text: "次に何を言うか考えず、相手の話を最後まで聞こう", category: "communication", difficulty: 2 },
        { text: "小さなことで誰かに助けを求めよう——役に立つ喜びをプレゼントしよう", category: "communication", difficulty: 2 },
        { text: "今日誰かに「あなたを誇りに思う」と伝えよう", category: "communication", difficulty: 2 },
        { text: "きれいなものの写真を、説明なしで誰かに送ろう——美しさをシェアするだけでいい", category: "communication", difficulty: 1 },
        { text: "誰かをお茶・コーヒー・軽食に誘おう——オンラインでもいい", category: "communication", difficulty: 2 },
        { text: "家族に「愛してる」か「あなたがいてくれてよかった」と伝えよう", category: "communication", difficulty: 2 },
        { text: "誰かの趣味を聞き、本当に興味を持とう", category: "communication", difficulty: 2 },
        { text: "昔の友人にメッセージを送り、共有の思い出を話そう", category: "communication", difficulty: 2 },
        { text: "辛そうな人に、心の中でそっと温かい想いを送ろう", category: "communication", difficulty: 1 },
        { text: "列で誰かを先に通し、笑顔でいよう", category: "communication", difficulty: 1 },
        { text: "今日、誰かの成功を祝おう——小さなものでもいい", category: "communication", difficulty: 1 },
        { text: "楽しんだブログ・動画・投稿に1行ポジティブなコメントを書こう", category: "communication", difficulty: 1 },
        { text: "誰かの荷物を持つか、小さな手伝いを申し出よう", category: "communication", difficulty: 2 },
        { text: "「本当に調子はどう？」と聞き、本当の答えを待とう", category: "communication", difficulty: 2 },
        { text: "誰かを思い出させたもののスクリーンショットを送ろう", category: "communication", difficulty: 1 },
        { text: "家でも外食でも、料理を褒めてみよう", category: "communication", difficulty: 1 },
        { text: "今日誰かと別れる時、いつもより温かくさよならを言おう", category: "communication", difficulty: 1 },
        { text: "今日誰かに面白い豆知識を教えよう", category: "communication", difficulty: 1 },
        { text: "近所の方に調子を聞いてみよう", category: "communication", difficulty: 2 },
        { text: "曲・番組・本を誰かにおすすめし、理由も伝えよう", category: "communication", difficulty: 2 },
        { text: "会いたい人に「あなたのことを思ってるよ」と書いて送ろう", category: "communication", difficulty: 2 },
        { text: "自分自身に感謝しよう——本当に心を込めて", category: "communication", difficulty: 1 },
        { text: "誰かに、その人が知っていることを一つ教えてもらおう", category: "communication", difficulty: 2 },
        { text: "誰かの尊敬するところを一つ伝えよう", category: "communication", difficulty: 2 },
        { text: "今日誰かと一緒に笑おう——くだらないことでもいい", category: "communication", difficulty: 1 },
        { text: "しばらく連絡していない人に会う・電話する計画を立てよう", category: "communication", difficulty: 2 },
        { text: "今の気分をぴったり表すGIFを友人に送ろう", category: "communication", difficulty: 1 },
        { text: "「今日何が嬉しかった？」と誰かに聞いてみよう", category: "communication", difficulty: 2 },
        { text: "何かを成し遂げた人にサムズアップかハイタッチをしよう", category: "communication", difficulty: 1 },
        { text: "会話の中で相手の名前を呼ぼう——人は見てもらえていると感じる", category: "communication", difficulty: 1 },
        { text: "信頼できる人に悩みを一つ打ち明けよう——一緒に抱えてもらおう", category: "communication", difficulty: 2 },
        { text: "心を込めて「おやすみ」か「おはよう」を伝えよう", category: "communication", difficulty: 1 },
        { text: "今日は褒め言葉を素直に受け取ろう——ただ「ありがとう」と言うだけでいい", category: "communication", difficulty: 1 },
        { text: "相手の話を遮らずに最後まで聞こう", category: "communication", difficulty: 1 },
        { text: "ずっと気になっていた小さなことを謝ろう", category: "communication", difficulty: 2 },
        { text: "お店の人にお気に入り商品を聞いてみよう", category: "communication", difficulty: 2 },
        { text: "誰かから来た嬉しいメッセージを保存し、読み返そう", category: "communication", difficulty: 1 },
        { text: "言葉の代わりに「そばにいるよ」を伝える絵文字を送ろう", category: "communication", difficulty: 1 },
        { text: "今日、鏡の自分に挨拶しよう——優しい言葉をかけよう", category: "communication", difficulty: 1 },
        { text: "待ってくれたこと、聞いてくれたこと、そこにいてくれたことに感謝しよう", category: "communication", difficulty: 1 },
        { text: "誰かと一緒の楽しい思い出を話題にしよう", category: "communication", difficulty: 2 },
        { text: "挑戦している人に、心のこもった励ましの言葉を贈ろう", category: "communication", difficulty: 2 },
        { text: "誰かの上手くいっていることに気づき、伝えよう", category: "communication", difficulty: 2 },
        { text: "忙しかったりストレスを抱えていることを知っている人に声をかけよう", category: "communication", difficulty: 2 },
        { text: "古いメッセージスレッドに「ふと思い出して——元気でいるといいな！」と返信しよう", category: "communication", difficulty: 2 },
        { text: "自分が話すより多く質問する会話をしてみよう", category: "communication", difficulty: 2 },
        { text: "誰かに「お大事に」と言い、心から意味を込めよう", category: "communication", difficulty: 1 },
        { text: "気になっていたのにまだ連絡していない人に連絡してみよう", category: "communication", difficulty: 2 },
        { text: "ずっと前にしてくれたことへの感謝を誰かに伝えよう", category: "communication", difficulty: 2 },
        { text: "誰かに「あなたの努力は意味がある」と伝えよう", category: "communication", difficulty: 2 },
        { text: "近くにいる人に、天気についての優しい一言を共有しよう", category: "communication", difficulty: 1 },
        { text: "誰かの週末の予定を聞き、本当に興味を持とう", category: "communication", difficulty: 1 },
        { text: "人前で誰かを褒めよう——その方が意味が深まる", category: "communication", difficulty: 2 },
        { text: "落ち込んでいそうな人に、解決しようとせずただ聞き役を申し出よう", category: "communication", difficulty: 2 },
        { text: "大切な人に10文字しか使えないとしたら何を伝えるか書こう", category: "communication", difficulty: 1 },
        { text: "窓から誰かに手を振って挨拶しよう", category: "communication", difficulty: 1 },
        { text: "楽しみにしていることを誰かに話そう", category: "communication", difficulty: 1 },
        { text: "今の景色の写真を友人に送り、今この瞬間を分かち合おう", category: "communication", difficulty: 1 },
        { text: "小さなクリエイターのコンテンツに優しいコメントを残そう", category: "communication", difficulty: 1 },
        { text: "「今日何かできることある？」と誰かに聞いてみよう", category: "communication", difficulty: 2 },
        { text: "「あなたがいてくれてよかった」と言葉で伝えよう", category: "communication", difficulty: 2 },
        { text: "大切な人を表す3つの言葉を書き、その人に伝えよう", category: "communication", difficulty: 2 },
        { text: "今日誰かを笑わせよう——ジョーク・表情・おかしな話など何でも", category: "communication", difficulty: 1 },
        { text: "今日の会話を「とても良い時間だった。ありがとう」で締めくくろう", category: "communication", difficulty: 1 },
        { text: "人生に影響を与えてくれた人を一人思い浮かべ、心の中で感謝しよう", category: "communication", difficulty: 1 },
        { text: "ただスクロールするのではなく、SNSに本音の投稿をしよう", category: "communication", difficulty: 2 },
        { text: "誰かの料理・仕事・努力が今日をより良くしてくれたと伝えよう", category: "communication", difficulty: 2 },
        { text: "今日、誰かを抱きしめよう（適切であれば）——いつもより少し長く", category: "communication", difficulty: 1 },

        // ╔══════════════════════════════════╗
        // ║  self — 120 challenges            ║
        // ╚══════════════════════════════════╝
        { text: "今日の自分にキャッチコピーをつけよう（例：「最善を尽くした人」）", category: "self", difficulty: 1 },
        { text: "今の気分を3つの絵文字だけで表し、メモに保存しよう", category: "self", difficulty: 1 },
        { text: "最近の自分のことで、こっそり誇りに思っていることを一つ書いてみよう", category: "self", difficulty: 1 },
        { text: "1年前の自分からメッセージを送るつもりで1〜2行書いてみよう", category: "self", difficulty: 2 },
        { text: "今日あった小さな良いことを3つ、紙かメモアプリに書き留めよう", category: "self", difficulty: 1 },
        { text: "寝る前に、明日の自分へ一行メッセージを書こう", category: "self", difficulty: 1 },
        { text: "今この瞬間の気持ちを一行日記として書こう", category: "self", difficulty: 1 },
        { text: "今日頑張ったことを一つだけ書いてみよう", category: "self", difficulty: 1 },
        { text: "今この瞬間、一番感謝していることを一つ挙げよう", category: "self", difficulty: 1 },
        { text: "少し恥ずかしくても、自分への褒め言葉を一つ書こう", category: "self", difficulty: 2 },
        { text: "過去の自分に伝えたい「ありがとう」を一つ考えよう", category: "self", difficulty: 1 },
        { text: "今頭にある3つのことを書き、集中するものを一つ丸で囲もう", category: "self", difficulty: 2 },
        { text: "今の気分をちょっとした落書きで描こう——絵の上手さは関係ない", category: "self", difficulty: 1 },
        { text: "怖かったのに乗り越えられたことを一つ書こう", category: "self", difficulty: 1 },
        { text: "生産性と無関係な、自分の好きなところを3つ挙げよう", category: "self", difficulty: 2 },
        { text: "3分タイマーをセットし、頭に浮かんだことを自由に書こう", category: "self", difficulty: 2 },
        { text: "今の人生のチャプターにタイトルをつけよう", category: "self", difficulty: 1 },
        { text: "6か月後の自分への手紙を書こう", category: "self", difficulty: 2 },
        { text: "気分を1〜10で評価し、その理由を一文で書こう", category: "self", difficulty: 1 },
        { text: "今日、あなたが頼まなくても体がしてくれたことを3つ挙げよう", category: "self", difficulty: 1 },
        { text: "自分についての思い込みで、実は正しくないかもしれないものを書こう", category: "self", difficulty: 2 },
        { text: "明日持ち歩きたい言葉を一つ選ぼう", category: "self", difficulty: 1 },
        { text: "今の気持ちを30秒の音声メモに録音しよう", category: "self", difficulty: 2 },
        { text: "最後に笑ったことを書き留めよう", category: "self", difficulty: 1 },
        { text: "謝るのをやめたいことを一つ書こう", category: "self", difficulty: 2 },
        { text: "一日のタイムラインを描き、一番幸せだった時間に印をつけよう", category: "self", difficulty: 2 },
        { text: "心が落ち着くものを5つ挙げよう——どんなに些細でもいい", category: "self", difficulty: 1 },
        { text: "自分への許可証を書こう：「私は〜していい」", category: "self", difficulty: 2 },
        { text: "理想の明日を3文で描写しよう", category: "self", difficulty: 1 },
        { text: "今週手放したいことを一つ書こう", category: "self", difficulty: 2 },
        { text: "今の気分を捉えた自撮りをしよう——自分だけの記念に", category: "self", difficulty: 1 },
        { text: "何があっても必ず気分が良くなることを一つ書こう", category: "self", difficulty: 1 },
        { text: "今の気分を表す曲を3曲挙げよう", category: "self", difficulty: 1 },
        { text: "スマホのギャラリーを開き、幸せな思い出を1分間眺めよう", category: "self", difficulty: 1 },
        { text: "今週設けたい、または守りたい境界線を一つ書こう", category: "self", difficulty: 2 },
        { text: "今の気分を表す3色を選び、落書きしよう", category: "self", difficulty: 1 },
        { text: "「今自分に何が必要か？」に正直に答えを書こう", category: "self", difficulty: 1 },
        { text: "得意なことを5つリストアップしよう——謙遜なし", category: "self", difficulty: 2 },
        { text: "未来の自分に今日のことで覚えていてほしいことを一つ書こう", category: "self", difficulty: 1 },
        { text: "最近誇りに思う決断について日記に書こう", category: "self", difficulty: 2 },
        { text: "今日の出来事を俳句にしよう（5-7-5音節）", category: "self", difficulty: 2 },
        { text: "今月改善した習慣を一つ挙げよう——どんなに小さくてもいい", category: "self", difficulty: 1 },
        { text: "ToDoリストの代わりに「できたことリスト」を作ろう——今日やったことをすべて書く", category: "self", difficulty: 1 },
        { text: "最後にもらった褒め言葉を書き、しっかり受け取ろう", category: "self", difficulty: 1 },
        { text: "今週の写真を一枚選び、キャプションをつけよう", category: "self", difficulty: 1 },
        { text: "見落としているかもしれない日常の小さな贅沢を3つ挙げよう", category: "self", difficulty: 1 },
        { text: "映画評論家のように、今日の感想を一文で書こう", category: "self", difficulty: 1 },
        { text: "今の気分が天気だったら、天気予報は何？書いてみよう", category: "self", difficulty: 1 },
        { text: "安心・平和な気持ちになれる場所を3つ挙げよう", category: "self", difficulty: 1 },
        { text: "10歳の自分に伝えたいことを一つ書こう", category: "self", difficulty: 2 },
        { text: "今日を正確に6語で表現しよう", category: "self", difficulty: 1 },
        { text: "考えすぎていることを書き、ノートを閉じよう", category: "self", difficulty: 2 },
        { text: "今日した勇気のいる小さなことを一つ挙げよう", category: "self", difficulty: 1 },
        { text: "「しないことリスト」を作ろう：今日心配しなくていいことを3つ", category: "self", difficulty: 1 },
        { text: "今シーズンやりたいことミニバケットリストを5つ作ろう", category: "self", difficulty: 2 },
        { text: "今日が昨日と違ったことを一つ書こう", category: "self", difficulty: 1 },
        { text: "安心感と愛情を感じさせてくれる人を3人挙げよう", category: "self", difficulty: 1 },
        { text: "「私は〜を自分に許す」から始まる一文を書こう", category: "self", difficulty: 2 },
        { text: "空白のメモを開き、思い浮かんだ最初の5語を書こう", category: "self", difficulty: 1 },
        { text: "理想の週末を3つの箇条書きで描写しよう", category: "self", difficulty: 1 },
        { text: "実は思っているより小さい恐れを一つ書こう", category: "self", difficulty: 2 },
        { text: "エネルギーを1〜10で評価し、1上げるためにできることを一つ書こう", category: "self", difficulty: 1 },
        { text: "今日のサウンドトラックがあるとしたら何の曲？書いてみよう", category: "self", difficulty: 1 },
        { text: "体の事実だけを使って、自分の素敵なところを一つ書こう", category: "self", difficulty: 1 },
        { text: "人生にもっと増やしたいことを一つ書こう", category: "self", difficulty: 1 },
        { text: "今日に色をつけるとしたら何色？その理由は？", category: "self", difficulty: 1 },
        { text: "スマホの写真で今月を表す小さなコラージュを作ろう", category: "self", difficulty: 2 },
        { text: "楽しみにしていることを一つ書こう——ささやかなことでもいい", category: "self", difficulty: 1 },
        { text: "この文を完成させよう：「実は自分では思っているより上手くやっているのは…だから」", category: "self", difficulty: 1 },
        { text: "今日頑張ってくれた体の部位への短いお礼を書こう", category: "self", difficulty: 1 },
        { text: "嬉しくなる音を3つ挙げよう", category: "self", difficulty: 1 },
        { text: "今月教えてもらった教訓を一つ書こう", category: "self", difficulty: 2 },
        { text: "今週の個人モットーを10語以内で作ろう", category: "self", difficulty: 1 },
        { text: "始めたいことと、やめたいことを一つずつ書こう", category: "self", difficulty: 2 },
        { text: "理想のだらだらする日を3文で描写しよう", category: "self", difficulty: 1 },
        { text: "自分の強さに自分で驚いた経験について書こう", category: "self", difficulty: 2 },
        { text: "今週のそれぞれの日を表す絵文字を選ぼう", category: "self", difficulty: 1 },
        { text: "5年後の自分へメッセージを書こう", category: "self", difficulty: 2 },
        { text: "特に意識せずに上手くなったことを3つ挙げよう", category: "self", difficulty: 1 },
        { text: "人生のこの時期について覚えておきたいことを一つ書こう", category: "self", difficulty: 2 },
        { text: "メモにミニムードボードを作ろう：目標のための3枚の画像と3つの言葉", category: "self", difficulty: 2 },
        { text: "今日体験した小さな喜びについて書こう", category: "self", difficulty: 1 },
        { text: "今見えているもので感謝できるものを5つ挙げよう", category: "self", difficulty: 1 },
        { text: "「今日私は〜を選ぶ」から始まる一文を書こう", category: "self", difficulty: 1 },
        { text: "世界で一番好きな場所を3文で描写しよう", category: "self", difficulty: 1 },
        { text: "今日のことで記憶に刻みたいことを一つ書こう", category: "self", difficulty: 1 },
        { text: "今年したことで、過去の自分が驚くであろうことを一つ挙げよう", category: "self", difficulty: 2 },
        { text: "辛い瞬間を乗り越えるための3語のマントラを作ろう", category: "self", difficulty: 1 },
        { text: "派手でも刺激的でもないけど、日常生活で好きなことを一つ書こう", category: "self", difficulty: 1 },
        { text: "友人が優しくあなたを描写するとしたら何と言う？書いてみよう", category: "self", difficulty: 2 },
        { text: "今の時刻のスクリーンショットを撮り、この瞬間を一語で表そう", category: "self", difficulty: 1 },
        { text: "心が落ち着く食事・番組・人を書き留めよう", category: "self", difficulty: 1 },
        { text: "「うまくやれているよ」の合図として手に小さな星を描こう", category: "self", difficulty: 1 },
        { text: "本当に穏やかだった最後の瞬間について書こう——一瞬でもいい", category: "self", difficulty: 2 },
        { text: "今の生活で守りたいことを3つ挙げよう", category: "self", difficulty: 2 },
        { text: "「今日の本当の調子は？」に正直に答えよう", category: "self", difficulty: 1 },
        { text: "手放す言葉を一つ選ぼう（例：「べき」「できない」「失敗」）", category: "self", difficulty: 2 },
        { text: "次の文を完成させよう：「無限の勇気があったら、私は…」", category: "self", difficulty: 2 },
        { text: "誰も知らない、こっそり取り組んでいることを一行書こう", category: "self", difficulty: 1 },
        { text: "絶対に笑顔になれるシンプルなことを3つ挙げよう", category: "self", difficulty: 1 },
        { text: "「私はこれでいい」を明日目に入る場所に書こう", category: "self", difficulty: 1 },
        { text: "当たり前にしてしまっているスキルや長所を一つ挙げよう", category: "self", difficulty: 1 },
        { text: "今週の終わりにどう感じていたいか一文で描写しよう", category: "self", difficulty: 1 },
        { text: "自分の人生への小さなラブレターを書こう——2〜3行でいい", category: "self", difficulty: 2 },
        { text: "深呼吸して、頭に浮かんだ最初の言葉を書こう。それが今日の言葉。", category: "self", difficulty: 1 },
        { text: "今月の中で、自分を褒めていい成果を一つ書こう", category: "self", difficulty: 1 },
        { text: "今日の天気と今の内面がリンクするところを一つ挙げよう", category: "self", difficulty: 1 },
        { text: "今週の感想を一行レビューで書こう", category: "self", difficulty: 1 },
        { text: "落ち着く質感を3つ挙げよう（毛布・木・紙など）", category: "self", difficulty: 1 },
        { text: "友人に送る短い応援メッセージを書き、それを自分に読もう", category: "self", difficulty: 2 },
        { text: "今の自分の人生が映画ジャンルだとしたら何？書いてみよう", category: "self", difficulty: 1 },
        { text: "辛い日に一番支えになる自分の強みを一つ挙げよう", category: "self", difficulty: 1 },
        { text: "気になっているけどまだ探求していないことを書こう", category: "self", difficulty: 1 },
        { text: "次の文を完成させよう：「今日のベストな形は…」", category: "self", difficulty: 1 },

        // ╔══════════════════════════════════╗
        // ║  relax — 120 challenges           ║
        // ╚══════════════════════════════════╝
        { text: "5分間だけ通知をすべてオフにして、静けさを楽しもう", category: "relax", difficulty: 2 },
        { text: "お気に入りの香り（コーヒー・お茶・入浴剤など）をマインドフルに吸い込もう", category: "relax", difficulty: 1 },
        { text: "少し照明を暗くして、天井や壁をぼーっと1分間眺めよう", category: "relax", difficulty: 1 },
        { text: "寝る前にスマホを置き、両手をゆっくり3回握ったり開いたりしよう", category: "relax", difficulty: 1 },
        { text: "5分間スマホを置いて、お気に入りの飲み物をゆっくり楽しもう", category: "relax", difficulty: 1 },
        { text: "お風呂に入る前に深呼吸を3回しよう", category: "relax", difficulty: 1 },
        { text: "何もせず、お気に入りの曲を一曲聴こう", category: "relax", difficulty: 1 },
        { text: "部屋の照明を暗くして、1分間だけ目を閉じよう", category: "relax", difficulty: 1 },
        { text: "30秒だけ肩・首・目の周りをゆっくりほぐそう", category: "relax", difficulty: 1 },
        { text: "寝る前のSNSスクロールをいつもより5分早くやめよう", category: "relax", difficulty: 2 },
        { text: "ベッドかソファに横になり「今日はこれで十分」とつぶやこう", category: "relax", difficulty: 1 },
        { text: "ハンドクリーム・お茶・コーヒーなどの香りを1分間堪能しよう", category: "relax", difficulty: 2 },
        { text: "目を閉じて、周りの3つの異なる音を聴こう", category: "relax", difficulty: 1 },
        { text: "ボディスキャンをしよう：つま先から頭まで1分かけてゆっくり感じよう", category: "relax", difficulty: 1 },
        { text: "毛布にくるまって、2分間静かに座ろう", category: "relax", difficulty: 1 },
        { text: "ノイズキャンセリングヘッドホンか耳栓をして、1分間の静寂を楽しもう", category: "relax", difficulty: 1 },
        { text: "キャンドルを灯すか暖かいランプをつけ、30秒間明かりを眺めよう", category: "relax", difficulty: 1 },
        { text: "両手を胸に当て、30秒間心拍を感じよう", category: "relax", difficulty: 1 },
        { text: "温かいお湯をゆっくり飲み、体を伝わる感覚を感じよう", category: "relax", difficulty: 1 },
        { text: "本を一ページだけ読もう——スクリーンではなく、本物のページ", category: "relax", difficulty: 1 },
        { text: "窓辺に座り、何も考えずに2分間外を眺めよう", category: "relax", difficulty: 1 },
        { text: "自分の手を30秒間やさしくマッサージしよう", category: "relax", difficulty: 1 },
        { text: "靴を脱いで、30秒間足で床の質感を感じよう", category: "relax", difficulty: 1 },
        { text: "枕かぬいぐるみを10秒間ぎゅっと抱きしめよう", category: "relax", difficulty: 1 },
        { text: "4カウントで吸い、4カウント止め、4カウントで吐く。3回繰り返そう", category: "relax", difficulty: 1 },
        { text: "落ち着くプレイリストをかけて、3分間横になろう", category: "relax", difficulty: 1 },
        { text: "窓から雲・雨・木を2分間眺めよう", category: "relax", difficulty: 1 },
        { text: "腕をゆっくり頭の上に伸ばし、できるだけ大きくあくびしよう", category: "relax", difficulty: 1 },
        { text: "温かいお湯でゆっくり顔を洗おう——一滴一滴を感じながら", category: "relax", difficulty: 1 },
        { text: "床に1分間横になり、地面が体を支えてくれるのを感じよう", category: "relax", difficulty: 1 },
        { text: "スマホで自然の写真を2分間眺めよう——スクロールせず、ただ見るだけ", category: "relax", difficulty: 1 },
        { text: "温かいものを飲みながら何もしないようにしよう。ただ飲んで呼吸して", category: "relax", difficulty: 1 },
        { text: "一つを除いてすべてのブラウザタブとアプリを閉じよう。すっきりした画面をしばし楽しもう", category: "relax", difficulty: 2 },
        { text: "ローションやクリームをゆっくり手に塗り、質感をしっかり感じよう", category: "relax", difficulty: 1 },
        { text: "スマホを裏返して置き、ゆっくり10回呼吸しよう", category: "relax", difficulty: 1 },
        { text: "水の音を聴こう——蛇口・動画・雨音など", category: "relax", difficulty: 1 },
        { text: "家の中で一番くつろげる場所に座り、2分間ただそこにいよう", category: "relax", difficulty: 1 },
        { text: "次の3分間、完全に何もしない自分に許可を与えよう", category: "relax", difficulty: 1 },
        { text: "ASMRか穏やかな自然動画を2分間見よう", category: "relax", difficulty: 1 },
        { text: "温かいシャワーを浴びながら、水の感覚だけに集中しよう", category: "relax", difficulty: 2 },
        { text: "わざとあくびを3回しよう。体が自然とついてくる", category: "relax", difficulty: 1 },
        { text: "ペット・柔らかい布・自分の腕を1分間やさしくなでよう", category: "relax", difficulty: 1 },
        { text: "寝る前に1分間、月か星を眺めよう", category: "relax", difficulty: 1 },
        { text: "心の中に平和な場所を思い描き、1分間そこに居続けよう", category: "relax", difficulty: 1 },
        { text: "チョコレート・果物・キャンディを一粒ゆっくり食べよう——一瞬一瞬を味わって", category: "relax", difficulty: 1 },
        { text: "スマホをグレースケールモードに切り替えて1時間過ごそう", category: "relax", difficulty: 2 },
        { text: "5分タイマーをセットし、ただ存在しよう——タスクも目標もなしで", category: "relax", difficulty: 2 },
        { text: "仰向けに寝て腕を体の横に置こう。2分間自然に呼吸しよう", category: "relax", difficulty: 1 },
        { text: "部屋の照明を一つ消して、柔らかい雰囲気を楽しもう", category: "relax", difficulty: 1 },
        { text: "指先をこめかみにそっと当て、ゆっくり円を描こう", category: "relax", difficulty: 1 },
        { text: "部屋で一番柔らかいものを見つけ、30秒間持ち続けよう", category: "relax", difficulty: 1 },
        { text: "穏やかで幸せな時期を思い出させる曲を聴こう", category: "relax", difficulty: 1 },
        { text: "6メートル先のものを20秒間見て目を休めよう", category: "relax", difficulty: 1 },
        { text: "温かい飲み物を作り、両手でカップを包もう", category: "relax", difficulty: 1 },
        { text: "20から1まで、数字ごとに呼吸しながらゆっくり数えよう", category: "relax", difficulty: 1 },
        { text: "首をやさしく左・右・前・後ろにストレッチし、それぞれ5秒キープしよう", category: "relax", difficulty: 1 },
        { text: "柔らかい靴下かスリッパを履き、その温もりを味わおう", category: "relax", difficulty: 1 },
        { text: "今すぐ顎の力を抜こう——きっと食いしばっているはず", category: "relax", difficulty: 1 },
        { text: "目を閉じて、幸せな場所を1分間思い浮かべよう", category: "relax", difficulty: 1 },
        { text: "コップ一杯の水を飲もう——一口ずつ感じながらゆっくりと", category: "relax", difficulty: 1 },
        { text: "吐く息が吸う息の2倍の長さになるように3回呼吸しよう", category: "relax", difficulty: 1 },
        { text: "今すぐ眉間のしわを伸ばそう。おでこの力を完全に抜いて", category: "relax", difficulty: 1 },
        { text: "窓を少し開け、1分間外の世界の音を聴こう", category: "relax", difficulty: 1 },
        { text: "足首をやさしく円を描くように回そう——各方向10回", category: "relax", difficulty: 1 },
        { text: "自然の音のプレイリストをかけ、2分間目を閉じよう", category: "relax", difficulty: 1 },
        { text: "今すぐ肩の力を抜こう。どれだけ力が入っていたか気づくはず", category: "relax", difficulty: 1 },
        { text: "今夜は寝る前に枕に落ち着く香りをスプレーしよう", category: "relax", difficulty: 1 },
        { text: "暖炉の動画を見るか、薪の燃える音を2分間聴こう", category: "relax", difficulty: 1 },
        { text: "1分間の感謝瞑想をしよう：目を閉じて良いことを3つ思い浮かべる", category: "relax", difficulty: 1 },
        { text: "1分間、ゆっくりマインドフルに髪をとかそう", category: "relax", difficulty: 1 },
        { text: "脚を壁に立てかけて2分間休もう", category: "relax", difficulty: 1 },
        { text: "靴を脱いで、30秒間自由に足の指を動かそう", category: "relax", difficulty: 1 },
        { text: "バイノーラルビートかLo-fiミュージックを3分間聴こう", category: "relax", difficulty: 1 },
        { text: "「リラックス」と手のひらに書き、くつろぐための触覚リマインダーにしよう", category: "relax", difficulty: 1 },
        { text: "SNSアプリをすべて閉じて、30分間開けないでいよう", category: "relax", difficulty: 2 },
        { text: "温かいカップを頬に当て、やさしい熱を感じよう", category: "relax", difficulty: 1 },
        { text: "いつもより1分長くお風呂かシャワーに入ろう", category: "relax", difficulty: 1 },
        { text: "子守唄を歌うかハミングしよう——心の中でも OK", category: "relax", difficulty: 1 },
        { text: "体中の筋肉を5秒間ぎゅっと収縮させ、一気に力を抜こう", category: "relax", difficulty: 1 },
        { text: "床にあぐらをかいて座り、1分間呼吸しよう", category: "relax", difficulty: 1 },
        { text: "ローション・キャンドル・おやつなど心落ち着く香りを嗅いで深呼吸しよう", category: "relax", difficulty: 1 },
        { text: "今夜の残りの時間、すべての画面の明るさを下げよう", category: "relax", difficulty: 2 },
        { text: "目を閉じて、穏やかな湖の上を漂っているところを想像しよう", category: "relax", difficulty: 1 },
        { text: "両手を素早くこすり合わせ、閉じた目の上に当てよう。温もりを感じて", category: "relax", difficulty: 1 },
        { text: "2分間、意識して何もしないようにしよう——怠けではなく、休息", category: "relax", difficulty: 1 },
        { text: "「私には休息が必要だ」と一回声に出し、そのままくつろごう", category: "relax", difficulty: 1 },
        { text: "座った状態か横になった状態で、30秒間ゆっくり左右に揺れよう", category: "relax", difficulty: 1 },
        { text: "詩を一篇——ただ一篇だけ——できれば声に出してゆっくり読もう", category: "relax", difficulty: 2 },
        { text: "心が温かくなる古い写真を眺めよう", category: "relax", difficulty: 1 },
        { text: "次の食事は画面なしで食べよう", category: "relax", difficulty: 2 },
        { text: "今夜はいつもより10分早く布団に入ろう", category: "relax", difficulty: 2 },
        { text: "ゆっくり5回呼吸し、一息ごとに悩みを一つ手放そう", category: "relax", difficulty: 1 },
        { text: "スマホをサイレントモードにして30分間過ごそう", category: "relax", difficulty: 2 },
        { text: "緊張をほぐすため、顎をやさしく左右に動かそう", category: "relax", difficulty: 1 },
        { text: "目を閉じて、好きな質感を3つ思い浮かべよう（ベルベット・砂・温かいお湯など）", category: "relax", difficulty: 1 },
        { text: "できるだけゆっくり息を吐こう——8秒かけてみよう", category: "relax", difficulty: 1 },
        { text: "自分に静かにつぶやこう：「きっとうまくいく」", category: "relax", difficulty: 1 },
        { text: "今夜の予定を一つ手放し、何もしないことに変えよう", category: "relax", difficulty: 2 },
        { text: "部屋の中で一番暖かい場所を見つけ、そこに落ち着こう", category: "relax", difficulty: 1 },
        { text: "今すぐ一番楽な服に着替えよう", category: "relax", difficulty: 1 },
        { text: "夕日を、動画でもいいから眺めながらゆっくり呼吸しよう", category: "relax", difficulty: 1 },
        { text: "何もないのに10秒間やさしく微笑もう。脳はそれを信じる", category: "relax", difficulty: 1 },
        { text: "指先で手のひらに30秒間ゆっくり円を描こう", category: "relax", difficulty: 1 },
        { text: "冷たいタオルをおでこに当て、1分間休もう", category: "relax", difficulty: 1 },
        { text: "波の音を2分間聴こう——本物でも録音でもいい", category: "relax", difficulty: 1 },
        { text: "お気に入りの毛布でブリトーのようにくるまろう。しばらくそこに居よう", category: "relax", difficulty: 1 },
        { text: "30秒間、自分の前腕をやさしくなでよう——自己癒しは本物", category: "relax", difficulty: 1 },
        { text: "椅子の中の体の重さを感じよう。重力に身を任せて", category: "relax", difficulty: 1 },
        { text: "鼻から吸い、口から吐く。ゆっくり5回繰り返そう", category: "relax", difficulty: 1 },
        { text: "温かい飲み物を両手で包み、熱が染み込む感覚を感じよう", category: "relax", difficulty: 1 },
        { text: "好きな色を思い浮かべ、それに包まれているところを想像しよう", category: "relax", difficulty: 1 },
        { text: "テーブルか枕に頭を60秒間だけ置こう", category: "relax", difficulty: 1 },
        { text: "30秒間鼻歌を歌おう——胸に振動を感じて", category: "relax", difficulty: 1 },
        { text: "聴こえるもの5つ・見えるもの4つ・触れるもの3つ・嗅げるもの2つを挙げよう", category: "relax", difficulty: 1 },

        // ╔══════════════════════════════════╗
        // ║  refresh — 120 challenges         ║
        // ╚══════════════════════════════════╝
        { text: "気分転換に、いつもと違うカップやマグカップを使おう", category: "refresh", difficulty: 1 },
        { text: "お気に入りの曲のサビだけ一回歌おう——口パクでもOK", category: "refresh", difficulty: 1 },
        { text: "1分タイマーをセットして、ストレッチ・あくび・肩回しを思い切りやろう", category: "refresh", difficulty: 2 },
        { text: "部屋でなんとなく目障りだったものを一つ片づけよう", category: "refresh", difficulty: 1 },
        { text: "コンビニで食べたことのないお菓子か飲み物を一つ選ぼう", category: "refresh", difficulty: 1 },
        { text: "気持ちいいところ（首・肩・背中など）を5分間ストレッチしよう", category: "refresh", difficulty: 1 },
        { text: "窓を開けて、30秒間だけ外の空気を深呼吸しよう", category: "refresh", difficulty: 1 },
        { text: "普段聴かない音楽ジャンルの曲を一曲聴いてみよう", category: "refresh", difficulty: 2 },
        { text: "ずっと気になっていた部屋の一か所を10秒だけ片づけよう", category: "refresh", difficulty: 1 },
        { text: "気分リセットに冷たい水か温かいお茶を一杯飲もう", category: "refresh", difficulty: 1 },
        { text: "背筋を伸ばして、肩を10回まわそう", category: "refresh", difficulty: 1 },
        { text: "普段読まないニュースや本のジャンルのトピックを一つ読んでみよう", category: "refresh", difficulty: 2 },
        { text: "冷たい水で手を洗い、その感覚をしっかり感じよう", category: "refresh", difficulty: 1 },
        { text: "机や棚の上のものを一つ並び替えよう", category: "refresh", difficulty: 1 },
        { text: "今着ているシャツが問題なくても、別のシャツに着替えよう", category: "refresh", difficulty: 1 },
        { text: "部屋で一曲分踊ろう——誰も見ていないから大丈夫", category: "refresh", difficulty: 1 },
        { text: "顔に冷たい水をかけ、リセットの感覚を味わおう", category: "refresh", difficulty: 1 },
        { text: "靴を履いて30秒間立ってみよう。スリッパとの違いを感じて", category: "refresh", difficulty: 1 },
        { text: "利き手でない方で何かを食べてみよう", category: "refresh", difficulty: 1 },
        { text: "いつも最初に開くアプリとは別のアプリを開いてみよう", category: "refresh", difficulty: 1 },
        { text: "今すぐ立ち上がって、ジャンピングジャックを10回やろう", category: "refresh", difficulty: 1 },
        { text: "スマホの壁紙を、気分が良くなるものに変えよう", category: "refresh", difficulty: 1 },
        { text: "バッグの中身を全部出して、本当に必要なものだけ戻そう", category: "refresh", difficulty: 2 },
        { text: "部屋のものを普段とは違う角度で撮影しよう", category: "refresh", difficulty: 1 },
        { text: "スクワットを10回しよう——5回でも3回でも、何回でもOK", category: "refresh", difficulty: 1 },
        { text: "思わず体を動かしたくなる曲をかけよう", category: "refresh", difficulty: 1 },
        { text: "読んでいないメールマガジンを一つ登録解除しよう", category: "refresh", difficulty: 1 },
        { text: "二度と見ない写真をスマホから3枚削除しよう", category: "refresh", difficulty: 1 },
        { text: "面白い動画を1分間見て、笑うに任せよう", category: "refresh", difficulty: 1 },
        { text: "脱ぎっぱなしの服を一枚たたむか掛けよう", category: "refresh", difficulty: 1 },
        { text: "今日はいつもと違う風味のお茶・コーヒー・ジュースを試してみよう", category: "refresh", difficulty: 1 },
        { text: "次のタスクは別の部屋か場所でやってみよう", category: "refresh", difficulty: 1 },
        { text: "日中に歯を磨こう——即効フレッシュリスタート", category: "refresh", difficulty: 1 },
        { text: "キッチンに行き、おやつを取ってパーティーみたいに立ったまま食べよう", category: "refresh", difficulty: 1 },
        { text: "スマホの画面を拭こう。きっと思ってるより汚れているはず", category: "refresh", difficulty: 1 },
        { text: "壁か机を使って腕立て伏せを3回やろう", category: "refresh", difficulty: 1 },
        { text: "スマホのアプリを整理し、便利なものを前面に出そう", category: "refresh", difficulty: 2 },
        { text: "Wikipediaをランダムに開き、新しいことを一つ学ぼう", category: "refresh", difficulty: 2 },
        { text: "お湯が沸くのを待つ間、つま先立ちをしよう", category: "refresh", difficulty: 1 },
        { text: "ルームスプレーをしたり香りのする引き出しを開けて、空気を変えよう", category: "refresh", difficulty: 1 },
        { text: "机・カウンター・テーブルのどれか一つを拭こう。すっきり感を楽しんで", category: "refresh", difficulty: 1 },
        { text: "利き手でない方で30秒書いてみよう。結果に笑おう", category: "refresh", difficulty: 1 },
        { text: "新しいタブを開いて「面白い雑学」を検索し、一つだけ読もう", category: "refresh", difficulty: 1 },
        { text: "鏡の前でおかしなポーズをとり、自分に微笑もう", category: "refresh", difficulty: 1 },
        { text: "ホーム画面のアイコンを色別に整理しよう", category: "refresh", difficulty: 2 },
        { text: "使ったことのない言葉を調べ、今日使ってみよう", category: "refresh", difficulty: 2 },
        { text: "一曲のエアギターかエアドラムを演奏しよう", category: "refresh", difficulty: 1 },
        { text: "すべてのブラウザタブを閉じ、新鮮なスタートを切ろう", category: "refresh", difficulty: 1 },
        { text: "新しい座り方を試そう——いつもと逆に足を組んでみよう", category: "refresh", difficulty: 1 },
        { text: "シャワーの最後に1分間、冷水で流してみよう", category: "refresh", difficulty: 2 },
        { text: "枕の冷たい面に裏返して、その感覚を楽しもう", category: "refresh", difficulty: 1 },
        { text: "片足で30秒立ち、反対側も同様に。バランスは爽快", category: "refresh", difficulty: 1 },
        { text: "元気が出るプレイリストをかけ、部屋の中を歩き回ろう", category: "refresh", difficulty: 1 },
        { text: "通知をすべてクリアしよう——すっきりしたスタートを", category: "refresh", difficulty: 1 },
        { text: "退屈なタスクをしながら笑顔を試そう。感じ方が変わるか見てみよう", category: "refresh", difficulty: 1 },
        { text: "今すぐベッドを整えよう——午後でもいい", category: "refresh", difficulty: 1 },
        { text: "試したことのないレシピを調べ、今週のためにブックマークしよう", category: "refresh", difficulty: 2 },
        { text: "今立っている場所で、つま先立ちを10回・かかとを下ろすのを10回しよう", category: "refresh", difficulty: 1 },
        { text: "「猫派？犬派？」みたいなランダムな楽しい質問を誰かに送ろう", category: "refresh", difficulty: 1 },
        { text: "部屋のものを一つ拾い上げ、本来の場所に戻そう", category: "refresh", difficulty: 1 },
        { text: "果物一切れかナッツひとつかみをリセットおやつとして食べよう", category: "refresh", difficulty: 1 },
        { text: "家の中で一番遠い部屋まで歩いて戻ろう——ミニ冒険", category: "refresh", difficulty: 1 },
        { text: "環境の BGM をまったく違うものに変えよう", category: "refresh", difficulty: 1 },
        { text: "フェイスマスクをするか、マインドフルに保湿剤を塗ろう", category: "refresh", difficulty: 1 },
        { text: "早口言葉を声に出して3回素早く言おう", category: "refresh", difficulty: 1 },
        { text: "キッチンの道具か食器を一つだけ洗おう", category: "refresh", difficulty: 1 },
        { text: "アルファベットを逆順にできるだけ早く書こう", category: "refresh", difficulty: 1 },
        { text: "次の30分間、いつもと違う座り方をしよう", category: "refresh", difficulty: 1 },
        { text: "引き出しを一つだけ整理しよう——一番小さいものでもいい", category: "refresh", difficulty: 2 },
        { text: "鏡で自分を褒めよう——声に出して言おう", category: "refresh", difficulty: 1 },
        { text: "普段炭酸なしを飲むなら炭酸水を（またはその逆を）飲もう", category: "refresh", difficulty: 1 },
        { text: "ペンを指の上で10秒バランスをとろう。成功するまで繰り返そう", category: "refresh", difficulty: 1 },
        { text: "TEDトークのサムネイルを一つ見て、見るかどうか決めよう。好奇心が大事", category: "refresh", difficulty: 1 },
        { text: "コイン・花・布など何かを30秒間じっくり近くで見よう", category: "refresh", difficulty: 1 },
        { text: "脳トレゲーム・パズル・言葉遊びを2分間やろう", category: "refresh", difficulty: 1 },
        { text: "スマホを別の部屋に置いて10分間過ごそう", category: "refresh", difficulty: 2 },
        { text: "お気に入りのメロディーを30秒間ハミングしてみよう", category: "refresh", difficulty: 1 },
        { text: "お手洗いへ行く遠回りルートを使ってみよう", category: "refresh", difficulty: 1 },
        { text: "植物に水をやろう、または想像でやろう——どちらもマインドフルネスになる", category: "refresh", difficulty: 1 },
        { text: "水を払うように手と足をブルブルと振ろう", category: "refresh", difficulty: 1 },
        { text: "ネットで名言を一つ読み、スマホに保存しよう", category: "refresh", difficulty: 1 },
        { text: "全く知らないトピックのポッドキャストを3分だけ聴こう", category: "refresh", difficulty: 2 },
        { text: "本か物を3つ積み上げてミニタワーを作ろう。ミニ建築チャレンジ", category: "refresh", difficulty: 1 },
        { text: "窓の外を見て、動いているものを5つ数えよう", category: "refresh", difficulty: 1 },
        { text: "目を閉じて、円・四角・三角形を描こう", category: "refresh", difficulty: 1 },
        { text: "単語を一つ思い浮かべ、韻を踏む言葉を5つ考えよう", category: "refresh", difficulty: 1 },
        { text: "棚一段・ポケット一つ・財布のコーナー一か所を整理しよう", category: "refresh", difficulty: 1 },
        { text: "今の気分に名前をつけよう（例：「ふわふわ火曜日エネルギー」）", category: "refresh", difficulty: 1 },
        { text: "つま先に触れてみよう。プレッシャーなし——今日の状態を確認するだけ", category: "refresh", difficulty: 1 },
        { text: "後で読むために自分に励ましのメールを送ろう", category: "refresh", difficulty: 2 },
        { text: "カードを一枚引き（実物でも想像でも）、今日のラッキーナンバーにしよう", category: "refresh", difficulty: 1 },
        { text: "今すぐ部屋の中で好きなものを3つ撮影しよう", category: "refresh", difficulty: 1 },
        { text: "行きたい場所をサクッと検索して写真を一枚眺めよう", category: "refresh", difficulty: 1 },
        { text: "10秒間、指・つま先・頭・全部をブルブル動かそう", category: "refresh", difficulty: 1 },
        { text: "ポケットかバッグの中身を全部出し、一つひとつ感謝して丁寧に戻そう", category: "refresh", difficulty: 1 },
        { text: "できそうな3つだけのミニToDoリストを作ろう", category: "refresh", difficulty: 1 },
        { text: "安全に10歩後ろ向きに歩こう——脳をびっくりさせるだけ", category: "refresh", difficulty: 1 },
        { text: "理由もなく持ち続けているものを一つ捨てよう", category: "refresh", difficulty: 1 },
        { text: "スマホの新しいアプリを試そう——1分間開いて見てみるだけでもいい", category: "refresh", difficulty: 1 },
        { text: "頭の中の曲のリズムに合わせて指をパチンとならそう", category: "refresh", difficulty: 1 },
        { text: "青いものを撮影しよう——空・ペン・マグカップ、何でもいい", category: "refresh", difficulty: 1 },
        { text: "今日の日付を声に出して言い「私はこの日にここにいた」と思おう", category: "refresh", difficulty: 1 },
        { text: "今日のメッセージで、一番使っていない絵文字を使おう", category: "refresh", difficulty: 1 },
        { text: "手首を円を描くように回そう——各方向10回", category: "refresh", difficulty: 1 },
        { text: "何年も聴いていない曲をハミングし、歌詞を思い出してみよう", category: "refresh", difficulty: 1 },
        { text: "鏡を見て、今日好きなところを一つ気づこう", category: "refresh", difficulty: 1 },
        { text: "ゆっくり一回転して、部屋をあらゆる角度から眺めよう", category: "refresh", difficulty: 1 },
        { text: "窓を少し開けて30秒間新鮮な空気を入れ、また閉めよう", category: "refresh", difficulty: 1 },
        { text: "作業場所に名前をつけよう——「集中コーナー」「まったりステーション」など", category: "refresh", difficulty: 1 },
        { text: "話せない言語で1から10まで数えよう（必要なら調べてOK）", category: "refresh", difficulty: 1 },
        { text: "近くにある物を一つ手に取り、変わった使い方を3つ考えよう", category: "refresh", difficulty: 1 },
        { text: "窓を開けて、外の空気の匂いを一回深呼吸しよう", category: "refresh", difficulty: 1 },

        // ╔══════════════════════════════════╗
        // ║  focus — 120 challenges           ║
        // ╚══════════════════════════════════╝
        { text: "一番頭に残っていることを一つだけ書こう", category: "focus", difficulty: 1 },
        { text: "やりたいことのスペースを作るため、机から一つ片づけよう", category: "focus", difficulty: 1 },
        { text: "やりたいことを3つ書き、今日やるものを一つに絞ろう", category: "focus", difficulty: 2 },
        { text: "3分タイマーをセットし、後回しにしていたタスクに取り掛かろう", category: "focus", difficulty: 2 },
        { text: "やらなければと思っていたことを、3分だけやってみよう", category: "focus", difficulty: 2 },
        { text: "机かバッグの中の一か所だけ整理しよう", category: "focus", difficulty: 1 },
        { text: "今日終わらせたいことを一つだけ書こう", category: "focus", difficulty: 1 },
        { text: "作業タイマーを3〜5分セットし、それだけに集中しよう", category: "focus", difficulty: 2 },
        { text: "しなくていいことを3つ書き、本当に一つを手放そう", category: "focus", difficulty: 2 },
        { text: "明日の自分を楽にするため、今できる小さなことを一つしよう", category: "focus", difficulty: 2 },
        { text: "たまっているメールかDMを一つだけ返信・処理しよう", category: "focus", difficulty: 1 },
        { text: "次の一週間で絶対にやりたいことを一つだけ書こう", category: "focus", difficulty: 2 },
        { text: "本当に必要なタブを一つ残して、すべてのタブを閉じよう", category: "focus", difficulty: 1 },
        { text: "次の一時間の明確な意図を一つ決めよう", category: "focus", difficulty: 1 },
        { text: "大きなタスクを3つの小さなステップに分け、最初の一つだけやろう", category: "focus", difficulty: 2 },
        { text: "次の15分間、スマホを別の部屋に置こう", category: "focus", difficulty: 2 },
        { text: "今夜寝る前に、明日のトップ3優先事項を書こう", category: "focus", difficulty: 2 },
        { text: "今すぐ古いメールを5件削除かアーカイブしよう", category: "focus", difficulty: 1 },
        { text: "今日を生産的に感じさせるたった一つのタスクを特定し、始めよう", category: "focus", difficulty: 2 },
        { text: "デジタルファイルかデスクトップを3分間整理しよう", category: "focus", difficulty: 2 },
        { text: "「今最も大切なことは…」から始まる一文を書こう", category: "focus", difficulty: 1 },
        { text: "5分ポモドーロタイマーをセットし、一つのタスクに全力集中しよう", category: "focus", difficulty: 2 },
        { text: "明日の最重要タスクに必要なものをすべて準備しよう", category: "focus", difficulty: 2 },
        { text: "「今日しないこと」リストを作ろう：待てることを3つ", category: "focus", difficulty: 1 },
        { text: "受信トレイにたまっているメッセージを3件まとめて返信しよう", category: "focus", difficulty: 2 },
        { text: "次の3日間のカレンダーを確認しよう——準備はできている？", category: "focus", difficulty: 2 },
        { text: "避けていたメールの件名を書こう。それが第一歩", category: "focus", difficulty: 2 },
        { text: "避けていた書類やプロジェクトを開き、最初の段落だけ読もう", category: "focus", difficulty: 1 },
        { text: "スマホをサイレントモードにして10分間ぶっ続けで作業しよう", category: "focus", difficulty: 2 },
        { text: "今やれば最も前進できる一つのことを挙げよう", category: "focus", difficulty: 1 },
        { text: "作業スペースから気が散るものを一つ取り除こう", category: "focus", difficulty: 1 },
        { text: "ToDoリストを緊急度順に並べ替えよう。実際に今日が期限のものは？", category: "focus", difficulty: 2 },
        { text: "避けていた小さな雑務を一つやろう（支払い・書類提出など）", category: "focus", difficulty: 2 },
        { text: "今週の目標を一文で設定しよう", category: "focus", difficulty: 1 },
        { text: "最重要プロジェクトを選び、60秒間次のステップを考えよう", category: "focus", difficulty: 1 },
        { text: "今週やるべきことのチェックリストを書こう——3項目だけでもいい", category: "focus", difficulty: 1 },
        { text: "ファイル・道具・本など一つを本来の場所に戻そう", category: "focus", difficulty: 1 },
        { text: "目標に関連するものを一ページ読もう", category: "focus", difficulty: 1 },
        { text: "書く必要があるものの一文を下書きしよう", category: "focus", difficulty: 1 },
        { text: "先延ばしにしていた決断を一つしよう——小さなものでもいい", category: "focus", difficulty: 2 },
        { text: "立ち上がって深呼吸し、次の30分の明確な意図を持って座り直そう", category: "focus", difficulty: 1 },
        { text: "時間を無駄にするアプリを一つアンインストールしよう", category: "focus", difficulty: 2 },
        { text: "明日の最重要タスクのために具体的な時間帯をブロックしよう", category: "focus", difficulty: 2 },
        { text: "前進を妨げていること一つと、その回避策を一つ書こう", category: "focus", difficulty: 2 },
        { text: "2分間のブレインダンプ：頭の中を全部書き出し、一つ実行に移そう", category: "focus", difficulty: 2 },
        { text: "5分間スキルを磨こう——タイピング・絵・学習中のことを練習しよう", category: "focus", difficulty: 2 },
        { text: "「これは一週間後に重要か？」と自問しよう。そうでなければ手放そう", category: "focus", difficulty: 1 },
        { text: "仕事に必要なアプリかツールを開こう——それが第一歩完了", category: "focus", difficulty: 1 },
        { text: "明日の食事を今決めておき、明日考えなくて済むようにしよう", category: "focus", difficulty: 2 },
        { text: "今日達成したことを一文でまとめて書こう", category: "focus", difficulty: 1 },
        { text: "気になっていたことをちょうど5分間調べよう", category: "focus", difficulty: 2 },
        { text: "身につけようとしている良い習慣を一回分やろう", category: "focus", difficulty: 1 },
        { text: "バックログから一つタスクを選び、最初のステップだけやろう", category: "focus", difficulty: 2 },
        { text: "今すぐ明日のバッグを準備しよう", category: "focus", difficulty: 1 },
        { text: "今日の優先事項を付箋一枚に書き、見える場所に貼ろう", category: "focus", difficulty: 1 },
        { text: "今週のメモを見直し、一つの気づきをハイライトしよう", category: "focus", difficulty: 2 },
        { text: "明日の理想の朝のルーティンを2分間計画しよう", category: "focus", difficulty: 1 },
        { text: "先延ばしにしていたメールを一通送ろう——完璧でなくていい", category: "focus", difficulty: 2 },
        { text: "今日コントロールできることを3つ挙げ、そこに集中しよう", category: "focus", difficulty: 1 },
        { text: "今まで締め切りのなかったものに期限を設けよう", category: "focus", difficulty: 2 },
        { text: "今夜デバイスを充電して、明日フル充電でスタートしよう", category: "focus", difficulty: 1 },
        { text: "時短になるキーボードショートカットを一つ覚えよう", category: "focus", difficulty: 1 },
        { text: "優先事項のスペースを作るため、今週犠牲にできることを一つ書こう", category: "focus", difficulty: 2 },
        { text: "一日の終わりに「できたこと」リストを作り、実際の成果を確認しよう", category: "focus", difficulty: 1 },
        { text: "スマホのホーム画面を3分間すっきりさせよう", category: "focus", difficulty: 1 },
        { text: "仕事を始める前に「今日は〜に集中する」と書こう", category: "focus", difficulty: 1 },
        { text: "未完了のループを一つ閉じよう：始めたのに完成していないことを終わらせよう", category: "focus", difficulty: 2 },
        { text: "次に聴くもの——ポッドキャスト・会議・動画——でメモを取ろう", category: "focus", difficulty: 2 },
        { text: "サブスクリプションを見直し、使っていないものを一つ解約しよう", category: "focus", difficulty: 2 },
        { text: "今夜の就寝時間を決め、明日を強くスタートさせよう", category: "focus", difficulty: 2 },
        { text: "取り組む前に、プロジェクトの短いアウトラインを書こう", category: "focus", difficulty: 2 },
        { text: "最重要タスクをToDoリストの一番上に置こう——文字通り最初に", category: "focus", difficulty: 1 },
        { text: "5分間何かをタイム計測しよう——実際にどれだけできるか気づくはず", category: "focus", difficulty: 2 },
        { text: "始めようと思っていた本の一章を読もう", category: "focus", difficulty: 2 },
        { text: "他の人を待っていることの「待ちリスト」を作ろう", category: "focus", difficulty: 2 },
        { text: "使いすぎているアプリにスクリーンタイム制限を設けよう", category: "focus", difficulty: 2 },
        { text: "寝る前に作業スペースを整えて、明日すっきりスタートできるようにしよう", category: "focus", difficulty: 1 },
        { text: "今夜明日の服を準備しよう——朝の決断が一つ減る", category: "focus", difficulty: 1 },
        { text: "フラッシュカード・ノート・練習など、何かを5分間勉強か復習しよう", category: "focus", difficulty: 2 },
        { text: "読もうと思っていたブックマークかリンクを一つ開き、今読もう", category: "focus", difficulty: 1 },
        { text: "今週を成功と感じさせる第一位のことを書こう", category: "focus", difficulty: 1 },
        { text: "「最も簡単な次の行動は何か？」と自問し、今すぐそれをやろう", category: "focus", difficulty: 1 },
        { text: "ToDoリストから一つチェックしよう。一番小さなものでもいい", category: "focus", difficulty: 1 },
        { text: "今週の健康的な食事を一つ計画しよう", category: "focus", difficulty: 2 },
        { text: "次のミーティングか会話で言いたいことを3つ書こう", category: "focus", difficulty: 2 },
        { text: "2分タイマーをセットして財布か小銭入れを整理しよう", category: "focus", difficulty: 1 },
        { text: "通知を永久にオフにするアプリを一つ選ぼう", category: "focus", difficulty: 1 },
        { text: "弱いか使い回していると知っているパスワードを一つ更新しよう", category: "focus", difficulty: 2 },
        { text: "今週の大切なことのリマインダーをスマホに設定しよう", category: "focus", difficulty: 1 },
        { text: "読書リストにあるものの最初の5行を読もう", category: "focus", difficulty: 1 },
        { text: "ファイルをより整理するための新しいフォルダを一つ作ろう", category: "focus", difficulty: 1 },
        { text: "ミニアクションプランを書こう：今のプロジェクトを進める3ステップ", category: "focus", difficulty: 2 },
        { text: "誰かに任せるか手伝いを頼めることを一つ特定しよう", category: "focus", difficulty: 2 },
        { text: "スクリーンタイムのレポートを見て、それをもとに一つの意図を設定しよう", category: "focus", difficulty: 2 },
        { text: "集中力を高めるため、短い運動を一セットしよう", category: "focus", difficulty: 1 },
        { text: "次のタスクを始める前に水を一杯飲もう。水分補給は集中力に効く", category: "focus", difficulty: 1 },
        { text: "今日の「作業終了時刻」を決め、それを守ろう", category: "focus", difficulty: 2 },
        { text: "パソコンかスマホの古いダウンロードファイルをアーカイブか削除しよう", category: "focus", difficulty: 1 },
        { text: "今月改善したいスキルを一つ書こう", category: "focus", difficulty: 1 },
        { text: "2分以内でできる小タスクを一つ完了しよう——そしてお祝いしよう", category: "focus", difficulty: 1 },
        { text: "先月の目標を振り返ろう。どうだったか？必要なら調整しよう", category: "focus", difficulty: 2 },
        { text: "大切なことに「はい」と言えるよう、今日「いいえ」と言うことを一つ選ぼう", category: "focus", difficulty: 2 },
        { text: "SNSを開く前に、まず一つ生産的なことをしよう", category: "focus", difficulty: 2 },
        { text: "真っ白なページの一番上に名前と今日の日付を書こう。新鮮なスタート", category: "focus", difficulty: 1 },
        { text: "今日の最重要タスクを完了する自分を視覚化しよう。さあ始めて", category: "focus", difficulty: 1 },
        { text: "30秒間作業スペースを整えよう。整った空間は整った心につながる", category: "focus", difficulty: 1 },
        { text: "何があっても今日中に終わらせるものを一つ選ぼう", category: "focus", difficulty: 2 },
        { text: "今日守る自分への約束を一つ書こう", category: "focus", difficulty: 1 },
        { text: "タイマーをセット：10分作業したら5分休憩で自分にご褒美", category: "focus", difficulty: 2 },
        { text: "タスクマネージャーを開き、最重要な3つにスターをつけよう", category: "focus", difficulty: 1 },
        { text: "次のタスクに必要なもの以外を机から全部片づけよう", category: "focus", difficulty: 1 },
        { text: "一文のコミットメントを書こう：「今夜までに、私は〜している」", category: "focus", difficulty: 1 },
        { text: "ToDoリストを見て、実際に重要でないものを一つ削除しよう", category: "focus", difficulty: 1 },
        { text: "30分後にアラームをセット。それまでに一つのタスクを終わらせる競争をしよう", category: "focus", difficulty: 2 },
        { text: "今気が散らないよう、後で読む記事を一つブックマークしよう", category: "focus", difficulty: 1 },
        { text: "今日の目標を誰かにメッセージしよう——アカウンタビリティは効果がある", category: "focus", difficulty: 2 },

        // --- Fill to 120 per category ---
        { text: "玄関ドアに立ち、一歩だけ外へ踏み出そう——今日のチャレンジはそれだけ", category: "outside", difficulty: 1 },
        { text: "通りを歩きながら、一番カラフルなものを撮影しよう", category: "outside", difficulty: 1 },
        { text: "外に出て、1分間雲の形を観察しよう", category: "outside", difficulty: 1 },
        { text: "木まで歩き、樹皮に触れ、10秒間その質感を感じよう", category: "outside", difficulty: 1 },
        { text: "1分間歩きながら、見えた窓の数を数えよう", category: "outside", difficulty: 1 },
        { text: "最寄りの道路標識まで歩き、声に出して読もう", category: "outside", difficulty: 1 },
        { text: "外に出て空気の匂いを嗅ごう——一言で表してみよう", category: "outside", difficulty: 1 },
        { text: "近くで一番暖かい野外スポットを見つけ、30秒間立とう", category: "outside", difficulty: 1 },

        { text: "友人に一言チェックイン——名前の後にクエスチョンマークだけでOK", category: "communication", difficulty: 1 },
        { text: "次に目が合った人に頷いて笑顔を向けよう", category: "communication", difficulty: 1 },
        { text: "今日誰かがしたことで気づいた一つの具体的なことを伝えよう", category: "communication", difficulty: 2 },
        { text: "何かを控えている人に「頑張れ」メッセージを送ろう", category: "communication", difficulty: 1 },
        { text: "最近どんな曲を聴いているか誰かに聞いてみよう", category: "communication", difficulty: 1 },
        { text: "今日の終わりに誰かに「また明日」と言おう——温かく心を込めて", category: "communication", difficulty: 1 },
        { text: "会話の中で、感謝していることを一つ誰かと共有しよう", category: "communication", difficulty: 2 },
        { text: "外見ではなく、発言について褒め言葉を伝えよう", category: "communication", difficulty: 2 },
        { text: "元気が必要かもしれない友人に心に響く言葉を転送しよう", category: "communication", difficulty: 1 },
        { text: "今週一番よかったことを誰かに聞こう", category: "communication", difficulty: 2 },
        { text: "家族に、ふと思い浮かんだ温かい一言をメッセージで送ろう", category: "communication", difficulty: 1 },

        { text: "今日もたらしてくれたことへの感謝を一文で書こう", category: "self", difficulty: 1 },
        { text: "今感じている感情を、判断せずに名前をつけよう", category: "self", difficulty: 1 },
        { text: "友人にも持っていてほしいと思う自分の資質を一つ書こう", category: "self", difficulty: 1 },
        { text: "最近自分にしてあげた親切なことを3つ挙げよう", category: "self", difficulty: 1 },
        { text: "今日の「これで十分」がどんな姿かを一文で書こう", category: "self", difficulty: 1 },
        { text: "今のエネルギーレベルを動物で例えよう（眠い猫？忙しいミツバチ？）", category: "self", difficulty: 1 },

        { text: "目を閉じて、お腹の上下を感じながらゆっくり10回呼吸しよう", category: "relax", difficulty: 1 },
        { text: "たまった緊張を手放すため、10秒間やさしく手を振ろう", category: "relax", difficulty: 1 },
        { text: "完全に安心できる場所を思い描こう。30秒間、心の中でそこにいよう", category: "relax", difficulty: 1 },
        { text: "金属・ガラス・タイルなど冷たいものに触れ、その感覚を意識しよう", category: "relax", difficulty: 1 },
        { text: "目を閉じて2分間、雨の音を聴こう", category: "relax", difficulty: 1 },
        { text: "ゆっくり手を開いたり閉じたりを10回繰り返し、毎回伸びる感覚を感じよう", category: "relax", difficulty: 1 },

        { text: "血流を良くするために深めのスクワットを5回しよう", category: "refresh", difficulty: 1 },
        { text: "次のメモは違う色のペンを使おう——小さな変化、大きなシフト", category: "refresh", difficulty: 1 },
        { text: "部屋全体を抱きしめようとするように腕を広げてストレッチしよう", category: "refresh", difficulty: 1 },
        { text: "新しい手洗い方法を試そう——温水の代わりに冷水を使おう", category: "refresh", difficulty: 1 },
        { text: "家具を数センチだけ動かして、部屋の雰囲気の変化に気づこう", category: "refresh", difficulty: 1 },
        { text: "カメラロールで一番面白い写真を見つけ、10秒間眺めよう", category: "refresh", difficulty: 1 },
        { text: "腕を前向きに5回・後ろ向きに5回まわそう", category: "refresh", difficulty: 1 },
        { text: "いつもの飲み物を試したことのないものに変えよう", category: "refresh", difficulty: 1 },

        { text: "紙に「スタート」と書き、避けていたタスクの上に置こう", category: "focus", difficulty: 1 },
        { text: "一つのタブだけ残して残りは全部閉じよう——今すぐ", category: "focus", difficulty: 1 },
        { text: "先延ばしにしていたことを一つ選び、最初の30秒だけやることにコミットしよう", category: "focus", difficulty: 1 },
        { text: "夕食前に達成したいことを二語でまとめて書こう", category: "focus", difficulty: 1 }
    ]
};

